// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/models.proto

package org.technbolts.protobuf;

public final class RequestPBModel {
  private RequestPBModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage {
    // Use Request.newBuilder() to construct.
    private Request() {
      initFields();
    }
    private Request(boolean noInit) {}
    
    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.RequestPBModel.internal_static_org_technbolts_protobuf_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.RequestPBModel.internal_static_org_technbolts_protobuf_Request_fieldAccessorTable;
    }
    
    // optional uint64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private long id_ = 0L;
    public boolean hasId() { return hasId; }
    public long getId() { return id_; }
    
    // optional uint32 system_state = 2;
    public static final int SYSTEM_STATE_FIELD_NUMBER = 2;
    private boolean hasSystemState;
    private int systemState_ = 0;
    public boolean hasSystemState() { return hasSystemState; }
    public int getSystemState() { return systemState_; }
    
    // optional uint32 request_state = 3;
    public static final int REQUEST_STATE_FIELD_NUMBER = 3;
    private boolean hasRequestState;
    private int requestState_ = 0;
    public boolean hasRequestState() { return hasRequestState; }
    public int getRequestState() { return requestState_; }
    
    // optional int64 creation_date = 4;
    public static final int CREATION_DATE_FIELD_NUMBER = 4;
    private boolean hasCreationDate;
    private long creationDate_ = 0L;
    public boolean hasCreationDate() { return hasCreationDate; }
    public long getCreationDate() { return creationDate_; }
    
    // optional int64 last_update_date = 5;
    public static final int LAST_UPDATE_DATE_FIELD_NUMBER = 5;
    private boolean hasLastUpdateDate;
    private long lastUpdateDate_ = 0L;
    public boolean hasLastUpdateDate() { return hasLastUpdateDate; }
    public long getLastUpdateDate() { return lastUpdateDate_; }
    
    // optional int64 close_date = 6;
    public static final int CLOSE_DATE_FIELD_NUMBER = 6;
    private boolean hasCloseDate;
    private long closeDate_ = 0L;
    public boolean hasCloseDate() { return hasCloseDate; }
    public long getCloseDate() { return closeDate_; }
    
    // optional uint32 distribution_mode = 7;
    public static final int DISTRIBUTION_MODE_FIELD_NUMBER = 7;
    private boolean hasDistributionMode;
    private int distributionMode_ = 0;
    public boolean hasDistributionMode() { return hasDistributionMode; }
    public int getDistributionMode() { return distributionMode_; }
    
    // optional .org.technbolts.protobuf.Ref responsible = 8;
    public static final int RESPONSIBLE_FIELD_NUMBER = 8;
    private boolean hasResponsible;
    private org.technbolts.protobuf.CommonPBO.Ref responsible_;
    public boolean hasResponsible() { return hasResponsible; }
    public org.technbolts.protobuf.CommonPBO.Ref getResponsible() { return responsible_; }
    
    // optional .org.technbolts.protobuf.RequestDetails details = 10;
    public static final int DETAILS_FIELD_NUMBER = 10;
    private boolean hasDetails;
    private org.technbolts.protobuf.RequestPBModel.RequestDetails details_;
    public boolean hasDetails() { return hasDetails; }
    public org.technbolts.protobuf.RequestPBModel.RequestDetails getDetails() { return details_; }
    
    private void initFields() {
      responsible_ = org.technbolts.protobuf.CommonPBO.Ref.getDefaultInstance();
      details_ = org.technbolts.protobuf.RequestPBModel.RequestDetails.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (hasResponsible()) {
        if (!getResponsible().isInitialized()) return false;
      }
      if (hasDetails()) {
        if (!getDetails().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeUInt64(1, getId());
      }
      if (hasSystemState()) {
        output.writeUInt32(2, getSystemState());
      }
      if (hasRequestState()) {
        output.writeUInt32(3, getRequestState());
      }
      if (hasCreationDate()) {
        output.writeInt64(4, getCreationDate());
      }
      if (hasLastUpdateDate()) {
        output.writeInt64(5, getLastUpdateDate());
      }
      if (hasCloseDate()) {
        output.writeInt64(6, getCloseDate());
      }
      if (hasDistributionMode()) {
        output.writeUInt32(7, getDistributionMode());
      }
      if (hasResponsible()) {
        output.writeMessage(8, getResponsible());
      }
      if (hasDetails()) {
        output.writeMessage(10, getDetails());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, getId());
      }
      if (hasSystemState()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, getSystemState());
      }
      if (hasRequestState()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, getRequestState());
      }
      if (hasCreationDate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, getCreationDate());
      }
      if (hasLastUpdateDate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, getLastUpdateDate());
      }
      if (hasCloseDate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, getCloseDate());
      }
      if (hasDistributionMode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, getDistributionMode());
      }
      if (hasResponsible()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getResponsible());
      }
      if (hasDetails()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, getDetails());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.RequestPBModel.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.RequestPBModel.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.RequestPBModel.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.RequestPBModel.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.RequestPBModel.Request result;
      
      // Construct using org.technbolts.protobuf.RequestPBModel.Request.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.RequestPBModel.Request();
        return builder;
      }
      
      protected org.technbolts.protobuf.RequestPBModel.Request internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.RequestPBModel.Request();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.RequestPBModel.Request.getDescriptor();
      }
      
      public org.technbolts.protobuf.RequestPBModel.Request getDefaultInstanceForType() {
        return org.technbolts.protobuf.RequestPBModel.Request.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.RequestPBModel.Request build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.RequestPBModel.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.RequestPBModel.Request buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        org.technbolts.protobuf.RequestPBModel.Request returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.RequestPBModel.Request) {
          return mergeFrom((org.technbolts.protobuf.RequestPBModel.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.RequestPBModel.Request other) {
        if (other == org.technbolts.protobuf.RequestPBModel.Request.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasSystemState()) {
          setSystemState(other.getSystemState());
        }
        if (other.hasRequestState()) {
          setRequestState(other.getRequestState());
        }
        if (other.hasCreationDate()) {
          setCreationDate(other.getCreationDate());
        }
        if (other.hasLastUpdateDate()) {
          setLastUpdateDate(other.getLastUpdateDate());
        }
        if (other.hasCloseDate()) {
          setCloseDate(other.getCloseDate());
        }
        if (other.hasDistributionMode()) {
          setDistributionMode(other.getDistributionMode());
        }
        if (other.hasResponsible()) {
          mergeResponsible(other.getResponsible());
        }
        if (other.hasDetails()) {
          mergeDetails(other.getDetails());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readUInt64());
              break;
            }
            case 16: {
              setSystemState(input.readUInt32());
              break;
            }
            case 24: {
              setRequestState(input.readUInt32());
              break;
            }
            case 32: {
              setCreationDate(input.readInt64());
              break;
            }
            case 40: {
              setLastUpdateDate(input.readInt64());
              break;
            }
            case 48: {
              setCloseDate(input.readInt64());
              break;
            }
            case 56: {
              setDistributionMode(input.readUInt32());
              break;
            }
            case 66: {
              org.technbolts.protobuf.CommonPBO.Ref.Builder subBuilder = org.technbolts.protobuf.CommonPBO.Ref.newBuilder();
              if (hasResponsible()) {
                subBuilder.mergeFrom(getResponsible());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setResponsible(subBuilder.buildPartial());
              break;
            }
            case 82: {
              org.technbolts.protobuf.RequestPBModel.RequestDetails.Builder subBuilder = org.technbolts.protobuf.RequestPBModel.RequestDetails.newBuilder();
              if (hasDetails()) {
                subBuilder.mergeFrom(getDetails());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setDetails(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional uint64 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public long getId() {
        return result.getId();
      }
      public Builder setId(long value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0L;
        return this;
      }
      
      // optional uint32 system_state = 2;
      public boolean hasSystemState() {
        return result.hasSystemState();
      }
      public int getSystemState() {
        return result.getSystemState();
      }
      public Builder setSystemState(int value) {
        result.hasSystemState = true;
        result.systemState_ = value;
        return this;
      }
      public Builder clearSystemState() {
        result.hasSystemState = false;
        result.systemState_ = 0;
        return this;
      }
      
      // optional uint32 request_state = 3;
      public boolean hasRequestState() {
        return result.hasRequestState();
      }
      public int getRequestState() {
        return result.getRequestState();
      }
      public Builder setRequestState(int value) {
        result.hasRequestState = true;
        result.requestState_ = value;
        return this;
      }
      public Builder clearRequestState() {
        result.hasRequestState = false;
        result.requestState_ = 0;
        return this;
      }
      
      // optional int64 creation_date = 4;
      public boolean hasCreationDate() {
        return result.hasCreationDate();
      }
      public long getCreationDate() {
        return result.getCreationDate();
      }
      public Builder setCreationDate(long value) {
        result.hasCreationDate = true;
        result.creationDate_ = value;
        return this;
      }
      public Builder clearCreationDate() {
        result.hasCreationDate = false;
        result.creationDate_ = 0L;
        return this;
      }
      
      // optional int64 last_update_date = 5;
      public boolean hasLastUpdateDate() {
        return result.hasLastUpdateDate();
      }
      public long getLastUpdateDate() {
        return result.getLastUpdateDate();
      }
      public Builder setLastUpdateDate(long value) {
        result.hasLastUpdateDate = true;
        result.lastUpdateDate_ = value;
        return this;
      }
      public Builder clearLastUpdateDate() {
        result.hasLastUpdateDate = false;
        result.lastUpdateDate_ = 0L;
        return this;
      }
      
      // optional int64 close_date = 6;
      public boolean hasCloseDate() {
        return result.hasCloseDate();
      }
      public long getCloseDate() {
        return result.getCloseDate();
      }
      public Builder setCloseDate(long value) {
        result.hasCloseDate = true;
        result.closeDate_ = value;
        return this;
      }
      public Builder clearCloseDate() {
        result.hasCloseDate = false;
        result.closeDate_ = 0L;
        return this;
      }
      
      // optional uint32 distribution_mode = 7;
      public boolean hasDistributionMode() {
        return result.hasDistributionMode();
      }
      public int getDistributionMode() {
        return result.getDistributionMode();
      }
      public Builder setDistributionMode(int value) {
        result.hasDistributionMode = true;
        result.distributionMode_ = value;
        return this;
      }
      public Builder clearDistributionMode() {
        result.hasDistributionMode = false;
        result.distributionMode_ = 0;
        return this;
      }
      
      // optional .org.technbolts.protobuf.Ref responsible = 8;
      public boolean hasResponsible() {
        return result.hasResponsible();
      }
      public org.technbolts.protobuf.CommonPBO.Ref getResponsible() {
        return result.getResponsible();
      }
      public Builder setResponsible(org.technbolts.protobuf.CommonPBO.Ref value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasResponsible = true;
        result.responsible_ = value;
        return this;
      }
      public Builder setResponsible(org.technbolts.protobuf.CommonPBO.Ref.Builder builderForValue) {
        result.hasResponsible = true;
        result.responsible_ = builderForValue.build();
        return this;
      }
      public Builder mergeResponsible(org.technbolts.protobuf.CommonPBO.Ref value) {
        if (result.hasResponsible() &&
            result.responsible_ != org.technbolts.protobuf.CommonPBO.Ref.getDefaultInstance()) {
          result.responsible_ =
            org.technbolts.protobuf.CommonPBO.Ref.newBuilder(result.responsible_).mergeFrom(value).buildPartial();
        } else {
          result.responsible_ = value;
        }
        result.hasResponsible = true;
        return this;
      }
      public Builder clearResponsible() {
        result.hasResponsible = false;
        result.responsible_ = org.technbolts.protobuf.CommonPBO.Ref.getDefaultInstance();
        return this;
      }
      
      // optional .org.technbolts.protobuf.RequestDetails details = 10;
      public boolean hasDetails() {
        return result.hasDetails();
      }
      public org.technbolts.protobuf.RequestPBModel.RequestDetails getDetails() {
        return result.getDetails();
      }
      public Builder setDetails(org.technbolts.protobuf.RequestPBModel.RequestDetails value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasDetails = true;
        result.details_ = value;
        return this;
      }
      public Builder setDetails(org.technbolts.protobuf.RequestPBModel.RequestDetails.Builder builderForValue) {
        result.hasDetails = true;
        result.details_ = builderForValue.build();
        return this;
      }
      public Builder mergeDetails(org.technbolts.protobuf.RequestPBModel.RequestDetails value) {
        if (result.hasDetails() &&
            result.details_ != org.technbolts.protobuf.RequestPBModel.RequestDetails.getDefaultInstance()) {
          result.details_ =
            org.technbolts.protobuf.RequestPBModel.RequestDetails.newBuilder(result.details_).mergeFrom(value).buildPartial();
        } else {
          result.details_ = value;
        }
        result.hasDetails = true;
        return this;
      }
      public Builder clearDetails() {
        result.hasDetails = false;
        result.details_ = org.technbolts.protobuf.RequestPBModel.RequestDetails.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.Request)
    }
    
    static {
      defaultInstance = new Request(true);
      org.technbolts.protobuf.RequestPBModel.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.Request)
  }
  
  public static final class RequestDetails extends
      com.google.protobuf.GeneratedMessage {
    // Use RequestDetails.newBuilder() to construct.
    private RequestDetails() {
      initFields();
    }
    private RequestDetails(boolean noInit) {}
    
    private static final RequestDetails defaultInstance;
    public static RequestDetails getDefaultInstance() {
      return defaultInstance;
    }
    
    public RequestDetails getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.RequestPBModel.internal_static_org_technbolts_protobuf_RequestDetails_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.RequestPBModel.internal_static_org_technbolts_protobuf_RequestDetails_fieldAccessorTable;
    }
    
    // optional string locale = 1;
    public static final int LOCALE_FIELD_NUMBER = 1;
    private boolean hasLocale;
    private java.lang.String locale_ = "";
    public boolean hasLocale() { return hasLocale; }
    public java.lang.String getLocale() { return locale_; }
    
    // optional .org.technbolts.protobuf.Ref created_by = 2;
    public static final int CREATED_BY_FIELD_NUMBER = 2;
    private boolean hasCreatedBy;
    private org.technbolts.protobuf.CommonPBO.Ref createdBy_;
    public boolean hasCreatedBy() { return hasCreatedBy; }
    public org.technbolts.protobuf.CommonPBO.Ref getCreatedBy() { return createdBy_; }
    
    // optional .org.technbolts.protobuf.Ref originator = 3;
    public static final int ORIGINATOR_FIELD_NUMBER = 3;
    private boolean hasOriginator;
    private org.technbolts.protobuf.CommonPBO.Ref originator_;
    public boolean hasOriginator() { return hasOriginator; }
    public org.technbolts.protobuf.CommonPBO.Ref getOriginator() { return originator_; }
    
    // optional .org.technbolts.protobuf.Ref last_updated_by = 4;
    public static final int LAST_UPDATED_BY_FIELD_NUMBER = 4;
    private boolean hasLastUpdatedBy;
    private org.technbolts.protobuf.CommonPBO.Ref lastUpdatedBy_;
    public boolean hasLastUpdatedBy() { return hasLastUpdatedBy; }
    public org.technbolts.protobuf.CommonPBO.Ref getLastUpdatedBy() { return lastUpdatedBy_; }
    
    // optional .org.technbolts.protobuf.Ref closed_by = 5;
    public static final int CLOSED_BY_FIELD_NUMBER = 5;
    private boolean hasClosedBy;
    private org.technbolts.protobuf.CommonPBO.Ref closedBy_;
    public boolean hasClosedBy() { return hasClosedBy; }
    public org.technbolts.protobuf.CommonPBO.Ref getClosedBy() { return closedBy_; }
    
    // repeated .org.technbolts.protobuf.RequestEvent event = 6;
    public static final int EVENT_FIELD_NUMBER = 6;
    private java.util.List<org.technbolts.protobuf.RequestPBModel.RequestEvent> event_ =
      java.util.Collections.emptyList();
    public java.util.List<org.technbolts.protobuf.RequestPBModel.RequestEvent> getEventList() {
      return event_;
    }
    public int getEventCount() { return event_.size(); }
    public org.technbolts.protobuf.RequestPBModel.RequestEvent getEvent(int index) {
      return event_.get(index);
    }
    
    // optional .org.technbolts.protobuf.Entity entity = 7;
    public static final int ENTITY_FIELD_NUMBER = 7;
    private boolean hasEntity;
    private org.technbolts.protobuf.CommonPBO.Entity entity_;
    public boolean hasEntity() { return hasEntity; }
    public org.technbolts.protobuf.CommonPBO.Entity getEntity() { return entity_; }
    
    private void initFields() {
      createdBy_ = org.technbolts.protobuf.CommonPBO.Ref.getDefaultInstance();
      originator_ = org.technbolts.protobuf.CommonPBO.Ref.getDefaultInstance();
      lastUpdatedBy_ = org.technbolts.protobuf.CommonPBO.Ref.getDefaultInstance();
      closedBy_ = org.technbolts.protobuf.CommonPBO.Ref.getDefaultInstance();
      entity_ = org.technbolts.protobuf.CommonPBO.Entity.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (hasCreatedBy()) {
        if (!getCreatedBy().isInitialized()) return false;
      }
      if (hasOriginator()) {
        if (!getOriginator().isInitialized()) return false;
      }
      if (hasLastUpdatedBy()) {
        if (!getLastUpdatedBy().isInitialized()) return false;
      }
      if (hasClosedBy()) {
        if (!getClosedBy().isInitialized()) return false;
      }
      for (org.technbolts.protobuf.RequestPBModel.RequestEvent element : getEventList()) {
        if (!element.isInitialized()) return false;
      }
      if (hasEntity()) {
        if (!getEntity().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasLocale()) {
        output.writeString(1, getLocale());
      }
      if (hasCreatedBy()) {
        output.writeMessage(2, getCreatedBy());
      }
      if (hasOriginator()) {
        output.writeMessage(3, getOriginator());
      }
      if (hasLastUpdatedBy()) {
        output.writeMessage(4, getLastUpdatedBy());
      }
      if (hasClosedBy()) {
        output.writeMessage(5, getClosedBy());
      }
      for (org.technbolts.protobuf.RequestPBModel.RequestEvent element : getEventList()) {
        output.writeMessage(6, element);
      }
      if (hasEntity()) {
        output.writeMessage(7, getEntity());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasLocale()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getLocale());
      }
      if (hasCreatedBy()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCreatedBy());
      }
      if (hasOriginator()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getOriginator());
      }
      if (hasLastUpdatedBy()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getLastUpdatedBy());
      }
      if (hasClosedBy()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getClosedBy());
      }
      for (org.technbolts.protobuf.RequestPBModel.RequestEvent element : getEventList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, element);
      }
      if (hasEntity()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getEntity());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.RequestPBModel.RequestDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.RequestPBModel.RequestDetails prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.RequestPBModel.RequestDetails result;
      
      // Construct using org.technbolts.protobuf.RequestPBModel.RequestDetails.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.RequestPBModel.RequestDetails();
        return builder;
      }
      
      protected org.technbolts.protobuf.RequestPBModel.RequestDetails internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.RequestPBModel.RequestDetails();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.RequestPBModel.RequestDetails.getDescriptor();
      }
      
      public org.technbolts.protobuf.RequestPBModel.RequestDetails getDefaultInstanceForType() {
        return org.technbolts.protobuf.RequestPBModel.RequestDetails.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.RequestPBModel.RequestDetails build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.RequestPBModel.RequestDetails buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.RequestPBModel.RequestDetails buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.event_ != java.util.Collections.EMPTY_LIST) {
          result.event_ =
            java.util.Collections.unmodifiableList(result.event_);
        }
        org.technbolts.protobuf.RequestPBModel.RequestDetails returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.RequestPBModel.RequestDetails) {
          return mergeFrom((org.technbolts.protobuf.RequestPBModel.RequestDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.RequestPBModel.RequestDetails other) {
        if (other == org.technbolts.protobuf.RequestPBModel.RequestDetails.getDefaultInstance()) return this;
        if (other.hasLocale()) {
          setLocale(other.getLocale());
        }
        if (other.hasCreatedBy()) {
          mergeCreatedBy(other.getCreatedBy());
        }
        if (other.hasOriginator()) {
          mergeOriginator(other.getOriginator());
        }
        if (other.hasLastUpdatedBy()) {
          mergeLastUpdatedBy(other.getLastUpdatedBy());
        }
        if (other.hasClosedBy()) {
          mergeClosedBy(other.getClosedBy());
        }
        if (!other.event_.isEmpty()) {
          if (result.event_.isEmpty()) {
            result.event_ = new java.util.ArrayList<org.technbolts.protobuf.RequestPBModel.RequestEvent>();
          }
          result.event_.addAll(other.event_);
        }
        if (other.hasEntity()) {
          mergeEntity(other.getEntity());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setLocale(input.readString());
              break;
            }
            case 18: {
              org.technbolts.protobuf.CommonPBO.Ref.Builder subBuilder = org.technbolts.protobuf.CommonPBO.Ref.newBuilder();
              if (hasCreatedBy()) {
                subBuilder.mergeFrom(getCreatedBy());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCreatedBy(subBuilder.buildPartial());
              break;
            }
            case 26: {
              org.technbolts.protobuf.CommonPBO.Ref.Builder subBuilder = org.technbolts.protobuf.CommonPBO.Ref.newBuilder();
              if (hasOriginator()) {
                subBuilder.mergeFrom(getOriginator());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setOriginator(subBuilder.buildPartial());
              break;
            }
            case 34: {
              org.technbolts.protobuf.CommonPBO.Ref.Builder subBuilder = org.technbolts.protobuf.CommonPBO.Ref.newBuilder();
              if (hasLastUpdatedBy()) {
                subBuilder.mergeFrom(getLastUpdatedBy());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLastUpdatedBy(subBuilder.buildPartial());
              break;
            }
            case 42: {
              org.technbolts.protobuf.CommonPBO.Ref.Builder subBuilder = org.technbolts.protobuf.CommonPBO.Ref.newBuilder();
              if (hasClosedBy()) {
                subBuilder.mergeFrom(getClosedBy());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setClosedBy(subBuilder.buildPartial());
              break;
            }
            case 50: {
              org.technbolts.protobuf.RequestPBModel.RequestEvent.Builder subBuilder = org.technbolts.protobuf.RequestPBModel.RequestEvent.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addEvent(subBuilder.buildPartial());
              break;
            }
            case 58: {
              org.technbolts.protobuf.CommonPBO.Entity.Builder subBuilder = org.technbolts.protobuf.CommonPBO.Entity.newBuilder();
              if (hasEntity()) {
                subBuilder.mergeFrom(getEntity());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setEntity(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional string locale = 1;
      public boolean hasLocale() {
        return result.hasLocale();
      }
      public java.lang.String getLocale() {
        return result.getLocale();
      }
      public Builder setLocale(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLocale = true;
        result.locale_ = value;
        return this;
      }
      public Builder clearLocale() {
        result.hasLocale = false;
        result.locale_ = getDefaultInstance().getLocale();
        return this;
      }
      
      // optional .org.technbolts.protobuf.Ref created_by = 2;
      public boolean hasCreatedBy() {
        return result.hasCreatedBy();
      }
      public org.technbolts.protobuf.CommonPBO.Ref getCreatedBy() {
        return result.getCreatedBy();
      }
      public Builder setCreatedBy(org.technbolts.protobuf.CommonPBO.Ref value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasCreatedBy = true;
        result.createdBy_ = value;
        return this;
      }
      public Builder setCreatedBy(org.technbolts.protobuf.CommonPBO.Ref.Builder builderForValue) {
        result.hasCreatedBy = true;
        result.createdBy_ = builderForValue.build();
        return this;
      }
      public Builder mergeCreatedBy(org.technbolts.protobuf.CommonPBO.Ref value) {
        if (result.hasCreatedBy() &&
            result.createdBy_ != org.technbolts.protobuf.CommonPBO.Ref.getDefaultInstance()) {
          result.createdBy_ =
            org.technbolts.protobuf.CommonPBO.Ref.newBuilder(result.createdBy_).mergeFrom(value).buildPartial();
        } else {
          result.createdBy_ = value;
        }
        result.hasCreatedBy = true;
        return this;
      }
      public Builder clearCreatedBy() {
        result.hasCreatedBy = false;
        result.createdBy_ = org.technbolts.protobuf.CommonPBO.Ref.getDefaultInstance();
        return this;
      }
      
      // optional .org.technbolts.protobuf.Ref originator = 3;
      public boolean hasOriginator() {
        return result.hasOriginator();
      }
      public org.technbolts.protobuf.CommonPBO.Ref getOriginator() {
        return result.getOriginator();
      }
      public Builder setOriginator(org.technbolts.protobuf.CommonPBO.Ref value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasOriginator = true;
        result.originator_ = value;
        return this;
      }
      public Builder setOriginator(org.technbolts.protobuf.CommonPBO.Ref.Builder builderForValue) {
        result.hasOriginator = true;
        result.originator_ = builderForValue.build();
        return this;
      }
      public Builder mergeOriginator(org.technbolts.protobuf.CommonPBO.Ref value) {
        if (result.hasOriginator() &&
            result.originator_ != org.technbolts.protobuf.CommonPBO.Ref.getDefaultInstance()) {
          result.originator_ =
            org.technbolts.protobuf.CommonPBO.Ref.newBuilder(result.originator_).mergeFrom(value).buildPartial();
        } else {
          result.originator_ = value;
        }
        result.hasOriginator = true;
        return this;
      }
      public Builder clearOriginator() {
        result.hasOriginator = false;
        result.originator_ = org.technbolts.protobuf.CommonPBO.Ref.getDefaultInstance();
        return this;
      }
      
      // optional .org.technbolts.protobuf.Ref last_updated_by = 4;
      public boolean hasLastUpdatedBy() {
        return result.hasLastUpdatedBy();
      }
      public org.technbolts.protobuf.CommonPBO.Ref getLastUpdatedBy() {
        return result.getLastUpdatedBy();
      }
      public Builder setLastUpdatedBy(org.technbolts.protobuf.CommonPBO.Ref value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLastUpdatedBy = true;
        result.lastUpdatedBy_ = value;
        return this;
      }
      public Builder setLastUpdatedBy(org.technbolts.protobuf.CommonPBO.Ref.Builder builderForValue) {
        result.hasLastUpdatedBy = true;
        result.lastUpdatedBy_ = builderForValue.build();
        return this;
      }
      public Builder mergeLastUpdatedBy(org.technbolts.protobuf.CommonPBO.Ref value) {
        if (result.hasLastUpdatedBy() &&
            result.lastUpdatedBy_ != org.technbolts.protobuf.CommonPBO.Ref.getDefaultInstance()) {
          result.lastUpdatedBy_ =
            org.technbolts.protobuf.CommonPBO.Ref.newBuilder(result.lastUpdatedBy_).mergeFrom(value).buildPartial();
        } else {
          result.lastUpdatedBy_ = value;
        }
        result.hasLastUpdatedBy = true;
        return this;
      }
      public Builder clearLastUpdatedBy() {
        result.hasLastUpdatedBy = false;
        result.lastUpdatedBy_ = org.technbolts.protobuf.CommonPBO.Ref.getDefaultInstance();
        return this;
      }
      
      // optional .org.technbolts.protobuf.Ref closed_by = 5;
      public boolean hasClosedBy() {
        return result.hasClosedBy();
      }
      public org.technbolts.protobuf.CommonPBO.Ref getClosedBy() {
        return result.getClosedBy();
      }
      public Builder setClosedBy(org.technbolts.protobuf.CommonPBO.Ref value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasClosedBy = true;
        result.closedBy_ = value;
        return this;
      }
      public Builder setClosedBy(org.technbolts.protobuf.CommonPBO.Ref.Builder builderForValue) {
        result.hasClosedBy = true;
        result.closedBy_ = builderForValue.build();
        return this;
      }
      public Builder mergeClosedBy(org.technbolts.protobuf.CommonPBO.Ref value) {
        if (result.hasClosedBy() &&
            result.closedBy_ != org.technbolts.protobuf.CommonPBO.Ref.getDefaultInstance()) {
          result.closedBy_ =
            org.technbolts.protobuf.CommonPBO.Ref.newBuilder(result.closedBy_).mergeFrom(value).buildPartial();
        } else {
          result.closedBy_ = value;
        }
        result.hasClosedBy = true;
        return this;
      }
      public Builder clearClosedBy() {
        result.hasClosedBy = false;
        result.closedBy_ = org.technbolts.protobuf.CommonPBO.Ref.getDefaultInstance();
        return this;
      }
      
      // repeated .org.technbolts.protobuf.RequestEvent event = 6;
      public java.util.List<org.technbolts.protobuf.RequestPBModel.RequestEvent> getEventList() {
        return java.util.Collections.unmodifiableList(result.event_);
      }
      public int getEventCount() {
        return result.getEventCount();
      }
      public org.technbolts.protobuf.RequestPBModel.RequestEvent getEvent(int index) {
        return result.getEvent(index);
      }
      public Builder setEvent(int index, org.technbolts.protobuf.RequestPBModel.RequestEvent value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.event_.set(index, value);
        return this;
      }
      public Builder setEvent(int index, org.technbolts.protobuf.RequestPBModel.RequestEvent.Builder builderForValue) {
        result.event_.set(index, builderForValue.build());
        return this;
      }
      public Builder addEvent(org.technbolts.protobuf.RequestPBModel.RequestEvent value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.event_.isEmpty()) {
          result.event_ = new java.util.ArrayList<org.technbolts.protobuf.RequestPBModel.RequestEvent>();
        }
        result.event_.add(value);
        return this;
      }
      public Builder addEvent(org.technbolts.protobuf.RequestPBModel.RequestEvent.Builder builderForValue) {
        if (result.event_.isEmpty()) {
          result.event_ = new java.util.ArrayList<org.technbolts.protobuf.RequestPBModel.RequestEvent>();
        }
        result.event_.add(builderForValue.build());
        return this;
      }
      public Builder addAllEvent(
          java.lang.Iterable<? extends org.technbolts.protobuf.RequestPBModel.RequestEvent> values) {
        if (result.event_.isEmpty()) {
          result.event_ = new java.util.ArrayList<org.technbolts.protobuf.RequestPBModel.RequestEvent>();
        }
        super.addAll(values, result.event_);
        return this;
      }
      public Builder clearEvent() {
        result.event_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional .org.technbolts.protobuf.Entity entity = 7;
      public boolean hasEntity() {
        return result.hasEntity();
      }
      public org.technbolts.protobuf.CommonPBO.Entity getEntity() {
        return result.getEntity();
      }
      public Builder setEntity(org.technbolts.protobuf.CommonPBO.Entity value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasEntity = true;
        result.entity_ = value;
        return this;
      }
      public Builder setEntity(org.technbolts.protobuf.CommonPBO.Entity.Builder builderForValue) {
        result.hasEntity = true;
        result.entity_ = builderForValue.build();
        return this;
      }
      public Builder mergeEntity(org.technbolts.protobuf.CommonPBO.Entity value) {
        if (result.hasEntity() &&
            result.entity_ != org.technbolts.protobuf.CommonPBO.Entity.getDefaultInstance()) {
          result.entity_ =
            org.technbolts.protobuf.CommonPBO.Entity.newBuilder(result.entity_).mergeFrom(value).buildPartial();
        } else {
          result.entity_ = value;
        }
        result.hasEntity = true;
        return this;
      }
      public Builder clearEntity() {
        result.hasEntity = false;
        result.entity_ = org.technbolts.protobuf.CommonPBO.Entity.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.RequestDetails)
    }
    
    static {
      defaultInstance = new RequestDetails(true);
      org.technbolts.protobuf.RequestPBModel.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.RequestDetails)
  }
  
  public static final class RequestEvent extends
      com.google.protobuf.GeneratedMessage {
    // Use RequestEvent.newBuilder() to construct.
    private RequestEvent() {
      initFields();
    }
    private RequestEvent(boolean noInit) {}
    
    private static final RequestEvent defaultInstance;
    public static RequestEvent getDefaultInstance() {
      return defaultInstance;
    }
    
    public RequestEvent getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.RequestPBModel.internal_static_org_technbolts_protobuf_RequestEvent_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.RequestPBModel.internal_static_org_technbolts_protobuf_RequestEvent_fieldAccessorTable;
    }
    
    // optional uint64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private long id_ = 0L;
    public boolean hasId() { return hasId; }
    public long getId() { return id_; }
    
    // optional uint32 type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private boolean hasType;
    private int type_ = 0;
    public boolean hasType() { return hasType; }
    public int getType() { return type_; }
    
    // optional int64 date = 3;
    public static final int DATE_FIELD_NUMBER = 3;
    private boolean hasDate;
    private long date_ = 0L;
    public boolean hasDate() { return hasDate; }
    public long getDate() { return date_; }
    
    // optional .org.technbolts.protobuf.Ref originated_by = 4;
    public static final int ORIGINATED_BY_FIELD_NUMBER = 4;
    private boolean hasOriginatedBy;
    private org.technbolts.protobuf.CommonPBO.Ref originatedBy_;
    public boolean hasOriginatedBy() { return hasOriginatedBy; }
    public org.technbolts.protobuf.CommonPBO.Ref getOriginatedBy() { return originatedBy_; }
    
    // optional .org.technbolts.protobuf.Ref destination = 5;
    public static final int DESTINATION_FIELD_NUMBER = 5;
    private boolean hasDestination;
    private org.technbolts.protobuf.CommonPBO.Ref destination_;
    public boolean hasDestination() { return hasDestination; }
    public org.technbolts.protobuf.CommonPBO.Ref getDestination() { return destination_; }
    
    // optional string comment = 6;
    public static final int COMMENT_FIELD_NUMBER = 6;
    private boolean hasComment;
    private java.lang.String comment_ = "";
    public boolean hasComment() { return hasComment; }
    public java.lang.String getComment() { return comment_; }
    
    // optional .org.technbolts.protobuf.Entity entity = 7;
    public static final int ENTITY_FIELD_NUMBER = 7;
    private boolean hasEntity;
    private org.technbolts.protobuf.CommonPBO.Entity entity_;
    public boolean hasEntity() { return hasEntity; }
    public org.technbolts.protobuf.CommonPBO.Entity getEntity() { return entity_; }
    
    private void initFields() {
      originatedBy_ = org.technbolts.protobuf.CommonPBO.Ref.getDefaultInstance();
      destination_ = org.technbolts.protobuf.CommonPBO.Ref.getDefaultInstance();
      entity_ = org.technbolts.protobuf.CommonPBO.Entity.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (hasOriginatedBy()) {
        if (!getOriginatedBy().isInitialized()) return false;
      }
      if (hasDestination()) {
        if (!getDestination().isInitialized()) return false;
      }
      if (hasEntity()) {
        if (!getEntity().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeUInt64(1, getId());
      }
      if (hasType()) {
        output.writeUInt32(2, getType());
      }
      if (hasDate()) {
        output.writeInt64(3, getDate());
      }
      if (hasOriginatedBy()) {
        output.writeMessage(4, getOriginatedBy());
      }
      if (hasDestination()) {
        output.writeMessage(5, getDestination());
      }
      if (hasComment()) {
        output.writeString(6, getComment());
      }
      if (hasEntity()) {
        output.writeMessage(7, getEntity());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, getId());
      }
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, getType());
      }
      if (hasDate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, getDate());
      }
      if (hasOriginatedBy()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getOriginatedBy());
      }
      if (hasDestination()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getDestination());
      }
      if (hasComment()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getComment());
      }
      if (hasEntity()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getEntity());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.RequestPBModel.RequestEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.RequestPBModel.RequestEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.RequestPBModel.RequestEvent result;
      
      // Construct using org.technbolts.protobuf.RequestPBModel.RequestEvent.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.RequestPBModel.RequestEvent();
        return builder;
      }
      
      protected org.technbolts.protobuf.RequestPBModel.RequestEvent internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.RequestPBModel.RequestEvent();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.RequestPBModel.RequestEvent.getDescriptor();
      }
      
      public org.technbolts.protobuf.RequestPBModel.RequestEvent getDefaultInstanceForType() {
        return org.technbolts.protobuf.RequestPBModel.RequestEvent.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.RequestPBModel.RequestEvent build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.RequestPBModel.RequestEvent buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.RequestPBModel.RequestEvent buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        org.technbolts.protobuf.RequestPBModel.RequestEvent returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.RequestPBModel.RequestEvent) {
          return mergeFrom((org.technbolts.protobuf.RequestPBModel.RequestEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.RequestPBModel.RequestEvent other) {
        if (other == org.technbolts.protobuf.RequestPBModel.RequestEvent.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (other.hasOriginatedBy()) {
          mergeOriginatedBy(other.getOriginatedBy());
        }
        if (other.hasDestination()) {
          mergeDestination(other.getDestination());
        }
        if (other.hasComment()) {
          setComment(other.getComment());
        }
        if (other.hasEntity()) {
          mergeEntity(other.getEntity());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readUInt64());
              break;
            }
            case 16: {
              setType(input.readUInt32());
              break;
            }
            case 24: {
              setDate(input.readInt64());
              break;
            }
            case 34: {
              org.technbolts.protobuf.CommonPBO.Ref.Builder subBuilder = org.technbolts.protobuf.CommonPBO.Ref.newBuilder();
              if (hasOriginatedBy()) {
                subBuilder.mergeFrom(getOriginatedBy());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setOriginatedBy(subBuilder.buildPartial());
              break;
            }
            case 42: {
              org.technbolts.protobuf.CommonPBO.Ref.Builder subBuilder = org.technbolts.protobuf.CommonPBO.Ref.newBuilder();
              if (hasDestination()) {
                subBuilder.mergeFrom(getDestination());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setDestination(subBuilder.buildPartial());
              break;
            }
            case 50: {
              setComment(input.readString());
              break;
            }
            case 58: {
              org.technbolts.protobuf.CommonPBO.Entity.Builder subBuilder = org.technbolts.protobuf.CommonPBO.Entity.newBuilder();
              if (hasEntity()) {
                subBuilder.mergeFrom(getEntity());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setEntity(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional uint64 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public long getId() {
        return result.getId();
      }
      public Builder setId(long value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0L;
        return this;
      }
      
      // optional uint32 type = 2;
      public boolean hasType() {
        return result.hasType();
      }
      public int getType() {
        return result.getType();
      }
      public Builder setType(int value) {
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = 0;
        return this;
      }
      
      // optional int64 date = 3;
      public boolean hasDate() {
        return result.hasDate();
      }
      public long getDate() {
        return result.getDate();
      }
      public Builder setDate(long value) {
        result.hasDate = true;
        result.date_ = value;
        return this;
      }
      public Builder clearDate() {
        result.hasDate = false;
        result.date_ = 0L;
        return this;
      }
      
      // optional .org.technbolts.protobuf.Ref originated_by = 4;
      public boolean hasOriginatedBy() {
        return result.hasOriginatedBy();
      }
      public org.technbolts.protobuf.CommonPBO.Ref getOriginatedBy() {
        return result.getOriginatedBy();
      }
      public Builder setOriginatedBy(org.technbolts.protobuf.CommonPBO.Ref value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasOriginatedBy = true;
        result.originatedBy_ = value;
        return this;
      }
      public Builder setOriginatedBy(org.technbolts.protobuf.CommonPBO.Ref.Builder builderForValue) {
        result.hasOriginatedBy = true;
        result.originatedBy_ = builderForValue.build();
        return this;
      }
      public Builder mergeOriginatedBy(org.technbolts.protobuf.CommonPBO.Ref value) {
        if (result.hasOriginatedBy() &&
            result.originatedBy_ != org.technbolts.protobuf.CommonPBO.Ref.getDefaultInstance()) {
          result.originatedBy_ =
            org.technbolts.protobuf.CommonPBO.Ref.newBuilder(result.originatedBy_).mergeFrom(value).buildPartial();
        } else {
          result.originatedBy_ = value;
        }
        result.hasOriginatedBy = true;
        return this;
      }
      public Builder clearOriginatedBy() {
        result.hasOriginatedBy = false;
        result.originatedBy_ = org.technbolts.protobuf.CommonPBO.Ref.getDefaultInstance();
        return this;
      }
      
      // optional .org.technbolts.protobuf.Ref destination = 5;
      public boolean hasDestination() {
        return result.hasDestination();
      }
      public org.technbolts.protobuf.CommonPBO.Ref getDestination() {
        return result.getDestination();
      }
      public Builder setDestination(org.technbolts.protobuf.CommonPBO.Ref value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasDestination = true;
        result.destination_ = value;
        return this;
      }
      public Builder setDestination(org.technbolts.protobuf.CommonPBO.Ref.Builder builderForValue) {
        result.hasDestination = true;
        result.destination_ = builderForValue.build();
        return this;
      }
      public Builder mergeDestination(org.technbolts.protobuf.CommonPBO.Ref value) {
        if (result.hasDestination() &&
            result.destination_ != org.technbolts.protobuf.CommonPBO.Ref.getDefaultInstance()) {
          result.destination_ =
            org.technbolts.protobuf.CommonPBO.Ref.newBuilder(result.destination_).mergeFrom(value).buildPartial();
        } else {
          result.destination_ = value;
        }
        result.hasDestination = true;
        return this;
      }
      public Builder clearDestination() {
        result.hasDestination = false;
        result.destination_ = org.technbolts.protobuf.CommonPBO.Ref.getDefaultInstance();
        return this;
      }
      
      // optional string comment = 6;
      public boolean hasComment() {
        return result.hasComment();
      }
      public java.lang.String getComment() {
        return result.getComment();
      }
      public Builder setComment(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasComment = true;
        result.comment_ = value;
        return this;
      }
      public Builder clearComment() {
        result.hasComment = false;
        result.comment_ = getDefaultInstance().getComment();
        return this;
      }
      
      // optional .org.technbolts.protobuf.Entity entity = 7;
      public boolean hasEntity() {
        return result.hasEntity();
      }
      public org.technbolts.protobuf.CommonPBO.Entity getEntity() {
        return result.getEntity();
      }
      public Builder setEntity(org.technbolts.protobuf.CommonPBO.Entity value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasEntity = true;
        result.entity_ = value;
        return this;
      }
      public Builder setEntity(org.technbolts.protobuf.CommonPBO.Entity.Builder builderForValue) {
        result.hasEntity = true;
        result.entity_ = builderForValue.build();
        return this;
      }
      public Builder mergeEntity(org.technbolts.protobuf.CommonPBO.Entity value) {
        if (result.hasEntity() &&
            result.entity_ != org.technbolts.protobuf.CommonPBO.Entity.getDefaultInstance()) {
          result.entity_ =
            org.technbolts.protobuf.CommonPBO.Entity.newBuilder(result.entity_).mergeFrom(value).buildPartial();
        } else {
          result.entity_ = value;
        }
        result.hasEntity = true;
        return this;
      }
      public Builder clearEntity() {
        result.hasEntity = false;
        result.entity_ = org.technbolts.protobuf.CommonPBO.Entity.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.RequestEvent)
    }
    
    static {
      defaultInstance = new RequestEvent(true);
      org.technbolts.protobuf.RequestPBModel.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.RequestEvent)
  }
  
  public static final class RequestList extends
      com.google.protobuf.GeneratedMessage {
    // Use RequestList.newBuilder() to construct.
    private RequestList() {
      initFields();
    }
    private RequestList(boolean noInit) {}
    
    private static final RequestList defaultInstance;
    public static RequestList getDefaultInstance() {
      return defaultInstance;
    }
    
    public RequestList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.RequestPBModel.internal_static_org_technbolts_protobuf_RequestList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.RequestPBModel.internal_static_org_technbolts_protobuf_RequestList_fieldAccessorTable;
    }
    
    // repeated uint32 request_id = 1;
    public static final int REQUEST_ID_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> requestId_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getRequestIdList() {
      return requestId_;
    }
    public int getRequestIdCount() { return requestId_.size(); }
    public int getRequestId(int index) {
      return requestId_.get(index);
    }
    
    // repeated .org.technbolts.protobuf.Request request = 2;
    public static final int REQUEST_FIELD_NUMBER = 2;
    private java.util.List<org.technbolts.protobuf.RequestPBModel.Request> request_ =
      java.util.Collections.emptyList();
    public java.util.List<org.technbolts.protobuf.RequestPBModel.Request> getRequestList() {
      return request_;
    }
    public int getRequestCount() { return request_.size(); }
    public org.technbolts.protobuf.RequestPBModel.Request getRequest(int index) {
      return request_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      for (org.technbolts.protobuf.RequestPBModel.Request element : getRequestList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int element : getRequestIdList()) {
        output.writeUInt32(1, element);
      }
      for (org.technbolts.protobuf.RequestPBModel.Request element : getRequestList()) {
        output.writeMessage(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int element : getRequestIdList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getRequestIdList().size();
      }
      for (org.technbolts.protobuf.RequestPBModel.Request element : getRequestList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.RequestPBModel.RequestList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.RequestPBModel.RequestList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.RequestPBModel.RequestList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.RequestPBModel.RequestList result;
      
      // Construct using org.technbolts.protobuf.RequestPBModel.RequestList.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.RequestPBModel.RequestList();
        return builder;
      }
      
      protected org.technbolts.protobuf.RequestPBModel.RequestList internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.RequestPBModel.RequestList();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.RequestPBModel.RequestList.getDescriptor();
      }
      
      public org.technbolts.protobuf.RequestPBModel.RequestList getDefaultInstanceForType() {
        return org.technbolts.protobuf.RequestPBModel.RequestList.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.RequestPBModel.RequestList build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.RequestPBModel.RequestList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.RequestPBModel.RequestList buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.requestId_ != java.util.Collections.EMPTY_LIST) {
          result.requestId_ =
            java.util.Collections.unmodifiableList(result.requestId_);
        }
        if (result.request_ != java.util.Collections.EMPTY_LIST) {
          result.request_ =
            java.util.Collections.unmodifiableList(result.request_);
        }
        org.technbolts.protobuf.RequestPBModel.RequestList returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.RequestPBModel.RequestList) {
          return mergeFrom((org.technbolts.protobuf.RequestPBModel.RequestList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.RequestPBModel.RequestList other) {
        if (other == org.technbolts.protobuf.RequestPBModel.RequestList.getDefaultInstance()) return this;
        if (!other.requestId_.isEmpty()) {
          if (result.requestId_.isEmpty()) {
            result.requestId_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.requestId_.addAll(other.requestId_);
        }
        if (!other.request_.isEmpty()) {
          if (result.request_.isEmpty()) {
            result.request_ = new java.util.ArrayList<org.technbolts.protobuf.RequestPBModel.Request>();
          }
          result.request_.addAll(other.request_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              addRequestId(input.readUInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addRequestId(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 18: {
              org.technbolts.protobuf.RequestPBModel.Request.Builder subBuilder = org.technbolts.protobuf.RequestPBModel.Request.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRequest(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated uint32 request_id = 1;
      public java.util.List<java.lang.Integer> getRequestIdList() {
        return java.util.Collections.unmodifiableList(result.requestId_);
      }
      public int getRequestIdCount() {
        return result.getRequestIdCount();
      }
      public int getRequestId(int index) {
        return result.getRequestId(index);
      }
      public Builder setRequestId(int index, int value) {
        result.requestId_.set(index, value);
        return this;
      }
      public Builder addRequestId(int value) {
        if (result.requestId_.isEmpty()) {
          result.requestId_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.requestId_.add(value);
        return this;
      }
      public Builder addAllRequestId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.requestId_.isEmpty()) {
          result.requestId_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.requestId_);
        return this;
      }
      public Builder clearRequestId() {
        result.requestId_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .org.technbolts.protobuf.Request request = 2;
      public java.util.List<org.technbolts.protobuf.RequestPBModel.Request> getRequestList() {
        return java.util.Collections.unmodifiableList(result.request_);
      }
      public int getRequestCount() {
        return result.getRequestCount();
      }
      public org.technbolts.protobuf.RequestPBModel.Request getRequest(int index) {
        return result.getRequest(index);
      }
      public Builder setRequest(int index, org.technbolts.protobuf.RequestPBModel.Request value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.request_.set(index, value);
        return this;
      }
      public Builder setRequest(int index, org.technbolts.protobuf.RequestPBModel.Request.Builder builderForValue) {
        result.request_.set(index, builderForValue.build());
        return this;
      }
      public Builder addRequest(org.technbolts.protobuf.RequestPBModel.Request value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.request_.isEmpty()) {
          result.request_ = new java.util.ArrayList<org.technbolts.protobuf.RequestPBModel.Request>();
        }
        result.request_.add(value);
        return this;
      }
      public Builder addRequest(org.technbolts.protobuf.RequestPBModel.Request.Builder builderForValue) {
        if (result.request_.isEmpty()) {
          result.request_ = new java.util.ArrayList<org.technbolts.protobuf.RequestPBModel.Request>();
        }
        result.request_.add(builderForValue.build());
        return this;
      }
      public Builder addAllRequest(
          java.lang.Iterable<? extends org.technbolts.protobuf.RequestPBModel.Request> values) {
        if (result.request_.isEmpty()) {
          result.request_ = new java.util.ArrayList<org.technbolts.protobuf.RequestPBModel.Request>();
        }
        super.addAll(values, result.request_);
        return this;
      }
      public Builder clearRequest() {
        result.request_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.RequestList)
    }
    
    static {
      defaultInstance = new RequestList(true);
      org.technbolts.protobuf.RequestPBModel.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.RequestList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_RequestDetails_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_RequestDetails_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_RequestEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_RequestEvent_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_RequestList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_RequestList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024request/models.proto\022\027org.technbolts.p" +
      "rotobuf\032\014common.proto\"\217\002\n\007Request\022\n\n\002id\030" +
      "\001 \001(\004\022\024\n\014system_state\030\002 \001(\r\022\025\n\rrequest_s" +
      "tate\030\003 \001(\r\022\025\n\rcreation_date\030\004 \001(\003\022\030\n\020las" +
      "t_update_date\030\005 \001(\003\022\022\n\nclose_date\030\006 \001(\003\022" +
      "\031\n\021distribution_mode\030\007 \001(\r\0221\n\013responsibl" +
      "e\030\010 \001(\0132\034.org.technbolts.protobuf.Ref\0228\n" +
      "\007details\030\n \001(\0132\'.org.technbolts.protobuf" +
      ".RequestDetails\"\323\002\n\016RequestDetails\022\016\n\006lo" +
      "cale\030\001 \001(\t\0220\n\ncreated_by\030\002 \001(\0132\034.org.tec",
      "hnbolts.protobuf.Ref\0220\n\noriginator\030\003 \001(\013" +
      "2\034.org.technbolts.protobuf.Ref\0225\n\017last_u" +
      "pdated_by\030\004 \001(\0132\034.org.technbolts.protobu" +
      "f.Ref\022/\n\tclosed_by\030\005 \001(\0132\034.org.technbolt" +
      "s.protobuf.Ref\0224\n\005event\030\006 \003(\0132%.org.tech" +
      "nbolts.protobuf.RequestEvent\022/\n\006entity\030\007" +
      " \001(\0132\037.org.technbolts.protobuf.Entity\"\340\001" +
      "\n\014RequestEvent\022\n\n\002id\030\001 \001(\004\022\014\n\004type\030\002 \001(\r" +
      "\022\014\n\004date\030\003 \001(\003\0223\n\roriginated_by\030\004 \001(\0132\034." +
      "org.technbolts.protobuf.Ref\0221\n\013destinati",
      "on\030\005 \001(\0132\034.org.technbolts.protobuf.Ref\022\017" +
      "\n\007comment\030\006 \001(\t\022/\n\006entity\030\007 \001(\0132\037.org.te" +
      "chnbolts.protobuf.Entity\"T\n\013RequestList\022" +
      "\022\n\nrequest_id\030\001 \003(\r\0221\n\007request\030\002 \003(\0132 .o" +
      "rg.technbolts.protobuf.RequestB+\n\027org.te" +
      "chnbolts.protobufB\016RequestPBModelH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_technbolts_protobuf_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_technbolts_protobuf_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_Request_descriptor,
              new java.lang.String[] { "Id", "SystemState", "RequestState", "CreationDate", "LastUpdateDate", "CloseDate", "DistributionMode", "Responsible", "Details", },
              org.technbolts.protobuf.RequestPBModel.Request.class,
              org.technbolts.protobuf.RequestPBModel.Request.Builder.class);
          internal_static_org_technbolts_protobuf_RequestDetails_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_technbolts_protobuf_RequestDetails_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_RequestDetails_descriptor,
              new java.lang.String[] { "Locale", "CreatedBy", "Originator", "LastUpdatedBy", "ClosedBy", "Event", "Entity", },
              org.technbolts.protobuf.RequestPBModel.RequestDetails.class,
              org.technbolts.protobuf.RequestPBModel.RequestDetails.Builder.class);
          internal_static_org_technbolts_protobuf_RequestEvent_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_org_technbolts_protobuf_RequestEvent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_RequestEvent_descriptor,
              new java.lang.String[] { "Id", "Type", "Date", "OriginatedBy", "Destination", "Comment", "Entity", },
              org.technbolts.protobuf.RequestPBModel.RequestEvent.class,
              org.technbolts.protobuf.RequestPBModel.RequestEvent.Builder.class);
          internal_static_org_technbolts_protobuf_RequestList_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_org_technbolts_protobuf_RequestList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_RequestList_descriptor,
              new java.lang.String[] { "RequestId", "Request", },
              org.technbolts.protobuf.RequestPBModel.RequestList.class,
              org.technbolts.protobuf.RequestPBModel.RequestList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.technbolts.protobuf.CommonPBO.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
