// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resource.proto

package org.technbolts.protobuf;

public final class ResourcePBO {
  private ResourcePBO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Resource extends
      com.google.protobuf.GeneratedMessage {
    // Use Resource.newBuilder() to construct.
    private Resource() {
      initFields();
    }
    private Resource(boolean noInit) {}
    
    private static final Resource defaultInstance;
    public static Resource getDefaultInstance() {
      return defaultInstance;
    }
    
    public Resource getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.ResourcePBO.internal_static_org_technbolts_protobuf_Resource_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.ResourcePBO.internal_static_org_technbolts_protobuf_Resource_fieldAccessorTable;
    }
    
    // optional uint32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional uint64 size = 3;
    public static final int SIZE_FIELD_NUMBER = 3;
    private boolean hasSize;
    private long size_ = 0L;
    public boolean hasSize() { return hasSize; }
    public long getSize() { return size_; }
    
    // optional string content_type = 4;
    public static final int CONTENT_TYPE_FIELD_NUMBER = 4;
    private boolean hasContentType;
    private java.lang.String contentType_ = "";
    public boolean hasContentType() { return hasContentType; }
    public java.lang.String getContentType() { return contentType_; }
    
    // repeated .org.technbolts.protobuf.Label label = 5;
    public static final int LABEL_FIELD_NUMBER = 5;
    private java.util.List<org.technbolts.protobuf.CommonPBO.Label> label_ =
      java.util.Collections.emptyList();
    public java.util.List<org.technbolts.protobuf.CommonPBO.Label> getLabelList() {
      return label_;
    }
    public int getLabelCount() { return label_.size(); }
    public org.technbolts.protobuf.CommonPBO.Label getLabel(int index) {
      return label_.get(index);
    }
    
    // optional uint32 chunkSize = 6 [default = 0];
    public static final int CHUNKSIZE_FIELD_NUMBER = 6;
    private boolean hasChunkSize;
    private int chunkSize_ = 0;
    public boolean hasChunkSize() { return hasChunkSize; }
    public int getChunkSize() { return chunkSize_; }
    
    // optional bytes value = 7;
    public static final int VALUE_FIELD_NUMBER = 7;
    private boolean hasValue;
    private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasValue() { return hasValue; }
    public com.google.protobuf.ByteString getValue() { return value_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeUInt32(1, getId());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      if (hasSize()) {
        output.writeUInt64(3, getSize());
      }
      if (hasContentType()) {
        output.writeString(4, getContentType());
      }
      for (org.technbolts.protobuf.CommonPBO.Label element : getLabelList()) {
        output.writeMessage(5, element);
      }
      if (hasChunkSize()) {
        output.writeUInt32(6, getChunkSize());
      }
      if (hasValue()) {
        output.writeBytes(7, getValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, getId());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      if (hasSize()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, getSize());
      }
      if (hasContentType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getContentType());
      }
      for (org.technbolts.protobuf.CommonPBO.Label element : getLabelList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, element);
      }
      if (hasChunkSize()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, getChunkSize());
      }
      if (hasValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.ResourcePBO.Resource parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.ResourcePBO.Resource parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.ResourcePBO.Resource parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.ResourcePBO.Resource parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.ResourcePBO.Resource parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.ResourcePBO.Resource parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.ResourcePBO.Resource parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.ResourcePBO.Resource parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.ResourcePBO.Resource parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.ResourcePBO.Resource parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.ResourcePBO.Resource prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.ResourcePBO.Resource result;
      
      // Construct using org.technbolts.protobuf.ResourcePBO.Resource.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.ResourcePBO.Resource();
        return builder;
      }
      
      protected org.technbolts.protobuf.ResourcePBO.Resource internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.ResourcePBO.Resource();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.ResourcePBO.Resource.getDescriptor();
      }
      
      public org.technbolts.protobuf.ResourcePBO.Resource getDefaultInstanceForType() {
        return org.technbolts.protobuf.ResourcePBO.Resource.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.ResourcePBO.Resource build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.ResourcePBO.Resource buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.ResourcePBO.Resource buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.label_ != java.util.Collections.EMPTY_LIST) {
          result.label_ =
            java.util.Collections.unmodifiableList(result.label_);
        }
        org.technbolts.protobuf.ResourcePBO.Resource returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.ResourcePBO.Resource) {
          return mergeFrom((org.technbolts.protobuf.ResourcePBO.Resource)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.ResourcePBO.Resource other) {
        if (other == org.technbolts.protobuf.ResourcePBO.Resource.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        if (other.hasContentType()) {
          setContentType(other.getContentType());
        }
        if (!other.label_.isEmpty()) {
          if (result.label_.isEmpty()) {
            result.label_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Label>();
          }
          result.label_.addAll(other.label_);
        }
        if (other.hasChunkSize()) {
          setChunkSize(other.getChunkSize());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readUInt32());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
            case 24: {
              setSize(input.readUInt64());
              break;
            }
            case 34: {
              setContentType(input.readString());
              break;
            }
            case 42: {
              org.technbolts.protobuf.CommonPBO.Label.Builder subBuilder = org.technbolts.protobuf.CommonPBO.Label.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addLabel(subBuilder.buildPartial());
              break;
            }
            case 48: {
              setChunkSize(input.readUInt32());
              break;
            }
            case 58: {
              setValue(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // optional uint32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional string name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // optional uint64 size = 3;
      public boolean hasSize() {
        return result.hasSize();
      }
      public long getSize() {
        return result.getSize();
      }
      public Builder setSize(long value) {
        result.hasSize = true;
        result.size_ = value;
        return this;
      }
      public Builder clearSize() {
        result.hasSize = false;
        result.size_ = 0L;
        return this;
      }
      
      // optional string content_type = 4;
      public boolean hasContentType() {
        return result.hasContentType();
      }
      public java.lang.String getContentType() {
        return result.getContentType();
      }
      public Builder setContentType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasContentType = true;
        result.contentType_ = value;
        return this;
      }
      public Builder clearContentType() {
        result.hasContentType = false;
        result.contentType_ = getDefaultInstance().getContentType();
        return this;
      }
      
      // repeated .org.technbolts.protobuf.Label label = 5;
      public java.util.List<org.technbolts.protobuf.CommonPBO.Label> getLabelList() {
        return java.util.Collections.unmodifiableList(result.label_);
      }
      public int getLabelCount() {
        return result.getLabelCount();
      }
      public org.technbolts.protobuf.CommonPBO.Label getLabel(int index) {
        return result.getLabel(index);
      }
      public Builder setLabel(int index, org.technbolts.protobuf.CommonPBO.Label value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.label_.set(index, value);
        return this;
      }
      public Builder setLabel(int index, org.technbolts.protobuf.CommonPBO.Label.Builder builderForValue) {
        result.label_.set(index, builderForValue.build());
        return this;
      }
      public Builder addLabel(org.technbolts.protobuf.CommonPBO.Label value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.label_.isEmpty()) {
          result.label_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Label>();
        }
        result.label_.add(value);
        return this;
      }
      public Builder addLabel(org.technbolts.protobuf.CommonPBO.Label.Builder builderForValue) {
        if (result.label_.isEmpty()) {
          result.label_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Label>();
        }
        result.label_.add(builderForValue.build());
        return this;
      }
      public Builder addAllLabel(
          java.lang.Iterable<? extends org.technbolts.protobuf.CommonPBO.Label> values) {
        if (result.label_.isEmpty()) {
          result.label_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Label>();
        }
        super.addAll(values, result.label_);
        return this;
      }
      public Builder clearLabel() {
        result.label_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional uint32 chunkSize = 6 [default = 0];
      public boolean hasChunkSize() {
        return result.hasChunkSize();
      }
      public int getChunkSize() {
        return result.getChunkSize();
      }
      public Builder setChunkSize(int value) {
        result.hasChunkSize = true;
        result.chunkSize_ = value;
        return this;
      }
      public Builder clearChunkSize() {
        result.hasChunkSize = false;
        result.chunkSize_ = 0;
        return this;
      }
      
      // optional bytes value = 7;
      public boolean hasValue() {
        return result.hasValue();
      }
      public com.google.protobuf.ByteString getValue() {
        return result.getValue();
      }
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = getDefaultInstance().getValue();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.Resource)
    }
    
    static {
      defaultInstance = new Resource(true);
      org.technbolts.protobuf.ResourcePBO.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.Resource)
  }
  
  public static final class ResourceChunk extends
      com.google.protobuf.GeneratedMessage {
    // Use ResourceChunk.newBuilder() to construct.
    private ResourceChunk() {
      initFields();
    }
    private ResourceChunk(boolean noInit) {}
    
    private static final ResourceChunk defaultInstance;
    public static ResourceChunk getDefaultInstance() {
      return defaultInstance;
    }
    
    public ResourceChunk getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.ResourcePBO.internal_static_org_technbolts_protobuf_ResourceChunk_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.ResourcePBO.internal_static_org_technbolts_protobuf_ResourceChunk_fieldAccessorTable;
    }
    
    // optional bytes value = 1;
    public static final int VALUE_FIELD_NUMBER = 1;
    private boolean hasValue;
    private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasValue() { return hasValue; }
    public com.google.protobuf.ByteString getValue() { return value_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasValue()) {
        output.writeBytes(1, getValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.ResourcePBO.ResourceChunk parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.ResourcePBO.ResourceChunk parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.ResourcePBO.ResourceChunk parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.ResourcePBO.ResourceChunk parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.ResourcePBO.ResourceChunk parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.ResourcePBO.ResourceChunk parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.ResourcePBO.ResourceChunk parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.ResourcePBO.ResourceChunk parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.ResourcePBO.ResourceChunk parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.ResourcePBO.ResourceChunk parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.ResourcePBO.ResourceChunk prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.ResourcePBO.ResourceChunk result;
      
      // Construct using org.technbolts.protobuf.ResourcePBO.ResourceChunk.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.ResourcePBO.ResourceChunk();
        return builder;
      }
      
      protected org.technbolts.protobuf.ResourcePBO.ResourceChunk internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.ResourcePBO.ResourceChunk();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.ResourcePBO.ResourceChunk.getDescriptor();
      }
      
      public org.technbolts.protobuf.ResourcePBO.ResourceChunk getDefaultInstanceForType() {
        return org.technbolts.protobuf.ResourcePBO.ResourceChunk.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.ResourcePBO.ResourceChunk build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.ResourcePBO.ResourceChunk buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.ResourcePBO.ResourceChunk buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        org.technbolts.protobuf.ResourcePBO.ResourceChunk returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.ResourcePBO.ResourceChunk) {
          return mergeFrom((org.technbolts.protobuf.ResourcePBO.ResourceChunk)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.ResourcePBO.ResourceChunk other) {
        if (other == org.technbolts.protobuf.ResourcePBO.ResourceChunk.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setValue(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // optional bytes value = 1;
      public boolean hasValue() {
        return result.hasValue();
      }
      public com.google.protobuf.ByteString getValue() {
        return result.getValue();
      }
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = getDefaultInstance().getValue();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.ResourceChunk)
    }
    
    static {
      defaultInstance = new ResourceChunk(true);
      org.technbolts.protobuf.ResourcePBO.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.ResourceChunk)
  }
  
  public static final class GetResource extends
      com.google.protobuf.GeneratedMessage {
    // Use GetResource.newBuilder() to construct.
    private GetResource() {
      initFields();
    }
    private GetResource(boolean noInit) {}
    
    private static final GetResource defaultInstance;
    public static GetResource getDefaultInstance() {
      return defaultInstance;
    }
    
    public GetResource getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.ResourcePBO.internal_static_org_technbolts_protobuf_GetResource_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.ResourcePBO.internal_static_org_technbolts_protobuf_GetResource_fieldAccessorTable;
    }
    
    // optional uint32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeUInt32(1, getId());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, getId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.ResourcePBO.GetResource parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.ResourcePBO.GetResource parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.ResourcePBO.GetResource parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.ResourcePBO.GetResource parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.ResourcePBO.GetResource parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.ResourcePBO.GetResource parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.ResourcePBO.GetResource parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.ResourcePBO.GetResource parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.ResourcePBO.GetResource parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.ResourcePBO.GetResource parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.ResourcePBO.GetResource prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.ResourcePBO.GetResource result;
      
      // Construct using org.technbolts.protobuf.ResourcePBO.GetResource.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.ResourcePBO.GetResource();
        return builder;
      }
      
      protected org.technbolts.protobuf.ResourcePBO.GetResource internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.ResourcePBO.GetResource();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.ResourcePBO.GetResource.getDescriptor();
      }
      
      public org.technbolts.protobuf.ResourcePBO.GetResource getDefaultInstanceForType() {
        return org.technbolts.protobuf.ResourcePBO.GetResource.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.ResourcePBO.GetResource build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.ResourcePBO.GetResource buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.ResourcePBO.GetResource buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        org.technbolts.protobuf.ResourcePBO.GetResource returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.ResourcePBO.GetResource) {
          return mergeFrom((org.technbolts.protobuf.ResourcePBO.GetResource)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.ResourcePBO.GetResource other) {
        if (other == org.technbolts.protobuf.ResourcePBO.GetResource.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readUInt32());
              break;
            }
          }
        }
      }
      
      
      // optional uint32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.GetResource)
    }
    
    static {
      defaultInstance = new GetResource(true);
      org.technbolts.protobuf.ResourcePBO.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.GetResource)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_Resource_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_Resource_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_ResourceChunk_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_ResourceChunk_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_GetResource_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_GetResource_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016resource.proto\022\027org.technbolts.protobu" +
      "f\032\014common.proto\"\234\001\n\010Resource\022\n\n\002id\030\001 \001(\r" +
      "\022\014\n\004name\030\002 \001(\t\022\014\n\004size\030\003 \001(\004\022\024\n\014content_" +
      "type\030\004 \001(\t\022-\n\005label\030\005 \003(\0132\036.org.technbol" +
      "ts.protobuf.Label\022\024\n\tchunkSize\030\006 \001(\r:\0010\022" +
      "\r\n\005value\030\007 \001(\014\"\036\n\rResourceChunk\022\r\n\005value" +
      "\030\001 \001(\014\"\031\n\013GetResource\022\n\n\002id\030\001 \001(\rB(\n\027org" +
      ".technbolts.protobufB\013ResourcePBOH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_technbolts_protobuf_Resource_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_technbolts_protobuf_Resource_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_Resource_descriptor,
              new java.lang.String[] { "Id", "Name", "Size", "ContentType", "Label", "ChunkSize", "Value", },
              org.technbolts.protobuf.ResourcePBO.Resource.class,
              org.technbolts.protobuf.ResourcePBO.Resource.Builder.class);
          internal_static_org_technbolts_protobuf_ResourceChunk_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_technbolts_protobuf_ResourceChunk_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_ResourceChunk_descriptor,
              new java.lang.String[] { "Value", },
              org.technbolts.protobuf.ResourcePBO.ResourceChunk.class,
              org.technbolts.protobuf.ResourcePBO.ResourceChunk.Builder.class);
          internal_static_org_technbolts_protobuf_GetResource_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_org_technbolts_protobuf_GetResource_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_GetResource_descriptor,
              new java.lang.String[] { "Id", },
              org.technbolts.protobuf.ResourcePBO.GetResource.class,
              org.technbolts.protobuf.ResourcePBO.GetResource.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.technbolts.protobuf.CommonPBO.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
