// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/role-api.proto

package org.technbolts.protobuf;

public final class RolePBCommand {
  private RolePBCommand() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CreateRole extends
      com.google.protobuf.GeneratedMessage {
    // Use CreateRole.newBuilder() to construct.
    private CreateRole() {
      initFields();
    }
    private CreateRole(boolean noInit) {}
    
    private static final CreateRole defaultInstance;
    public static CreateRole getDefaultInstance() {
      return defaultInstance;
    }
    
    public CreateRole getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.RolePBCommand.internal_static_org_technbolts_protobuf_CreateRole_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.RolePBCommand.internal_static_org_technbolts_protobuf_CreateRole_fieldAccessorTable;
    }
    
    // repeated .org.technbolts.protobuf.Role role = 1;
    public static final int ROLE_FIELD_NUMBER = 1;
    private java.util.List<org.technbolts.protobuf.UserPBModel.Role> role_ =
      java.util.Collections.emptyList();
    public java.util.List<org.technbolts.protobuf.UserPBModel.Role> getRoleList() {
      return role_;
    }
    public int getRoleCount() { return role_.size(); }
    public org.technbolts.protobuf.UserPBModel.Role getRole(int index) {
      return role_.get(index);
    }
    
    // optional bool id_only = 2 [default = false];
    public static final int ID_ONLY_FIELD_NUMBER = 2;
    private boolean hasIdOnly;
    private boolean idOnly_ = false;
    public boolean hasIdOnly() { return hasIdOnly; }
    public boolean getIdOnly() { return idOnly_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (org.technbolts.protobuf.UserPBModel.Role element : getRoleList()) {
        output.writeMessage(1, element);
      }
      if (hasIdOnly()) {
        output.writeBool(2, getIdOnly());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (org.technbolts.protobuf.UserPBModel.Role element : getRoleList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      if (hasIdOnly()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, getIdOnly());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.RolePBCommand.CreateRole parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.CreateRole parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.CreateRole parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.CreateRole parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.CreateRole parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.CreateRole parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.CreateRole parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.RolePBCommand.CreateRole parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.RolePBCommand.CreateRole parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.CreateRole parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.RolePBCommand.CreateRole prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.RolePBCommand.CreateRole result;
      
      // Construct using org.technbolts.protobuf.RolePBCommand.CreateRole.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.RolePBCommand.CreateRole();
        return builder;
      }
      
      protected org.technbolts.protobuf.RolePBCommand.CreateRole internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.RolePBCommand.CreateRole();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.RolePBCommand.CreateRole.getDescriptor();
      }
      
      public org.technbolts.protobuf.RolePBCommand.CreateRole getDefaultInstanceForType() {
        return org.technbolts.protobuf.RolePBCommand.CreateRole.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.RolePBCommand.CreateRole build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.RolePBCommand.CreateRole buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.RolePBCommand.CreateRole buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.role_ != java.util.Collections.EMPTY_LIST) {
          result.role_ =
            java.util.Collections.unmodifiableList(result.role_);
        }
        org.technbolts.protobuf.RolePBCommand.CreateRole returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.RolePBCommand.CreateRole) {
          return mergeFrom((org.technbolts.protobuf.RolePBCommand.CreateRole)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.RolePBCommand.CreateRole other) {
        if (other == org.technbolts.protobuf.RolePBCommand.CreateRole.getDefaultInstance()) return this;
        if (!other.role_.isEmpty()) {
          if (result.role_.isEmpty()) {
            result.role_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.Role>();
          }
          result.role_.addAll(other.role_);
        }
        if (other.hasIdOnly()) {
          setIdOnly(other.getIdOnly());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              org.technbolts.protobuf.UserPBModel.Role.Builder subBuilder = org.technbolts.protobuf.UserPBModel.Role.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRole(subBuilder.buildPartial());
              break;
            }
            case 16: {
              setIdOnly(input.readBool());
              break;
            }
          }
        }
      }
      
      
      // repeated .org.technbolts.protobuf.Role role = 1;
      public java.util.List<org.technbolts.protobuf.UserPBModel.Role> getRoleList() {
        return java.util.Collections.unmodifiableList(result.role_);
      }
      public int getRoleCount() {
        return result.getRoleCount();
      }
      public org.technbolts.protobuf.UserPBModel.Role getRole(int index) {
        return result.getRole(index);
      }
      public Builder setRole(int index, org.technbolts.protobuf.UserPBModel.Role value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.role_.set(index, value);
        return this;
      }
      public Builder setRole(int index, org.technbolts.protobuf.UserPBModel.Role.Builder builderForValue) {
        result.role_.set(index, builderForValue.build());
        return this;
      }
      public Builder addRole(org.technbolts.protobuf.UserPBModel.Role value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.role_.isEmpty()) {
          result.role_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.Role>();
        }
        result.role_.add(value);
        return this;
      }
      public Builder addRole(org.technbolts.protobuf.UserPBModel.Role.Builder builderForValue) {
        if (result.role_.isEmpty()) {
          result.role_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.Role>();
        }
        result.role_.add(builderForValue.build());
        return this;
      }
      public Builder addAllRole(
          java.lang.Iterable<? extends org.technbolts.protobuf.UserPBModel.Role> values) {
        if (result.role_.isEmpty()) {
          result.role_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.Role>();
        }
        super.addAll(values, result.role_);
        return this;
      }
      public Builder clearRole() {
        result.role_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional bool id_only = 2 [default = false];
      public boolean hasIdOnly() {
        return result.hasIdOnly();
      }
      public boolean getIdOnly() {
        return result.getIdOnly();
      }
      public Builder setIdOnly(boolean value) {
        result.hasIdOnly = true;
        result.idOnly_ = value;
        return this;
      }
      public Builder clearIdOnly() {
        result.hasIdOnly = false;
        result.idOnly_ = false;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.CreateRole)
    }
    
    static {
      defaultInstance = new CreateRole(true);
      org.technbolts.protobuf.RolePBCommand.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.CreateRole)
  }
  
  public static final class CreateRoleResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use CreateRoleResponse.newBuilder() to construct.
    private CreateRoleResponse() {
      initFields();
    }
    private CreateRoleResponse(boolean noInit) {}
    
    private static final CreateRoleResponse defaultInstance;
    public static CreateRoleResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public CreateRoleResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.RolePBCommand.internal_static_org_technbolts_protobuf_CreateRoleResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.RolePBCommand.internal_static_org_technbolts_protobuf_CreateRoleResponse_fieldAccessorTable;
    }
    
    // repeated .org.technbolts.protobuf.Error error = 1;
    public static final int ERROR_FIELD_NUMBER = 1;
    private java.util.List<org.technbolts.protobuf.CommonPBO.Error> error_ =
      java.util.Collections.emptyList();
    public java.util.List<org.technbolts.protobuf.CommonPBO.Error> getErrorList() {
      return error_;
    }
    public int getErrorCount() { return error_.size(); }
    public org.technbolts.protobuf.CommonPBO.Error getError(int index) {
      return error_.get(index);
    }
    
    // repeated .org.technbolts.protobuf.Role role = 2;
    public static final int ROLE_FIELD_NUMBER = 2;
    private java.util.List<org.technbolts.protobuf.UserPBModel.Role> role_ =
      java.util.Collections.emptyList();
    public java.util.List<org.technbolts.protobuf.UserPBModel.Role> getRoleList() {
      return role_;
    }
    public int getRoleCount() { return role_.size(); }
    public org.technbolts.protobuf.UserPBModel.Role getRole(int index) {
      return role_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (org.technbolts.protobuf.CommonPBO.Error element : getErrorList()) {
        output.writeMessage(1, element);
      }
      for (org.technbolts.protobuf.UserPBModel.Role element : getRoleList()) {
        output.writeMessage(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (org.technbolts.protobuf.CommonPBO.Error element : getErrorList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      for (org.technbolts.protobuf.UserPBModel.Role element : getRoleList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.RolePBCommand.CreateRoleResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.CreateRoleResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.CreateRoleResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.CreateRoleResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.CreateRoleResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.CreateRoleResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.CreateRoleResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.RolePBCommand.CreateRoleResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.RolePBCommand.CreateRoleResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.CreateRoleResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.RolePBCommand.CreateRoleResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.RolePBCommand.CreateRoleResponse result;
      
      // Construct using org.technbolts.protobuf.RolePBCommand.CreateRoleResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.RolePBCommand.CreateRoleResponse();
        return builder;
      }
      
      protected org.technbolts.protobuf.RolePBCommand.CreateRoleResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.RolePBCommand.CreateRoleResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.RolePBCommand.CreateRoleResponse.getDescriptor();
      }
      
      public org.technbolts.protobuf.RolePBCommand.CreateRoleResponse getDefaultInstanceForType() {
        return org.technbolts.protobuf.RolePBCommand.CreateRoleResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.RolePBCommand.CreateRoleResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.RolePBCommand.CreateRoleResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.RolePBCommand.CreateRoleResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.error_ != java.util.Collections.EMPTY_LIST) {
          result.error_ =
            java.util.Collections.unmodifiableList(result.error_);
        }
        if (result.role_ != java.util.Collections.EMPTY_LIST) {
          result.role_ =
            java.util.Collections.unmodifiableList(result.role_);
        }
        org.technbolts.protobuf.RolePBCommand.CreateRoleResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.RolePBCommand.CreateRoleResponse) {
          return mergeFrom((org.technbolts.protobuf.RolePBCommand.CreateRoleResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.RolePBCommand.CreateRoleResponse other) {
        if (other == org.technbolts.protobuf.RolePBCommand.CreateRoleResponse.getDefaultInstance()) return this;
        if (!other.error_.isEmpty()) {
          if (result.error_.isEmpty()) {
            result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
          }
          result.error_.addAll(other.error_);
        }
        if (!other.role_.isEmpty()) {
          if (result.role_.isEmpty()) {
            result.role_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.Role>();
          }
          result.role_.addAll(other.role_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              org.technbolts.protobuf.CommonPBO.Error.Builder subBuilder = org.technbolts.protobuf.CommonPBO.Error.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addError(subBuilder.buildPartial());
              break;
            }
            case 18: {
              org.technbolts.protobuf.UserPBModel.Role.Builder subBuilder = org.technbolts.protobuf.UserPBModel.Role.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRole(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .org.technbolts.protobuf.Error error = 1;
      public java.util.List<org.technbolts.protobuf.CommonPBO.Error> getErrorList() {
        return java.util.Collections.unmodifiableList(result.error_);
      }
      public int getErrorCount() {
        return result.getErrorCount();
      }
      public org.technbolts.protobuf.CommonPBO.Error getError(int index) {
        return result.getError(index);
      }
      public Builder setError(int index, org.technbolts.protobuf.CommonPBO.Error value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.error_.set(index, value);
        return this;
      }
      public Builder setError(int index, org.technbolts.protobuf.CommonPBO.Error.Builder builderForValue) {
        result.error_.set(index, builderForValue.build());
        return this;
      }
      public Builder addError(org.technbolts.protobuf.CommonPBO.Error value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.error_.isEmpty()) {
          result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
        }
        result.error_.add(value);
        return this;
      }
      public Builder addError(org.technbolts.protobuf.CommonPBO.Error.Builder builderForValue) {
        if (result.error_.isEmpty()) {
          result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
        }
        result.error_.add(builderForValue.build());
        return this;
      }
      public Builder addAllError(
          java.lang.Iterable<? extends org.technbolts.protobuf.CommonPBO.Error> values) {
        if (result.error_.isEmpty()) {
          result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
        }
        super.addAll(values, result.error_);
        return this;
      }
      public Builder clearError() {
        result.error_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .org.technbolts.protobuf.Role role = 2;
      public java.util.List<org.technbolts.protobuf.UserPBModel.Role> getRoleList() {
        return java.util.Collections.unmodifiableList(result.role_);
      }
      public int getRoleCount() {
        return result.getRoleCount();
      }
      public org.technbolts.protobuf.UserPBModel.Role getRole(int index) {
        return result.getRole(index);
      }
      public Builder setRole(int index, org.technbolts.protobuf.UserPBModel.Role value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.role_.set(index, value);
        return this;
      }
      public Builder setRole(int index, org.technbolts.protobuf.UserPBModel.Role.Builder builderForValue) {
        result.role_.set(index, builderForValue.build());
        return this;
      }
      public Builder addRole(org.technbolts.protobuf.UserPBModel.Role value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.role_.isEmpty()) {
          result.role_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.Role>();
        }
        result.role_.add(value);
        return this;
      }
      public Builder addRole(org.technbolts.protobuf.UserPBModel.Role.Builder builderForValue) {
        if (result.role_.isEmpty()) {
          result.role_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.Role>();
        }
        result.role_.add(builderForValue.build());
        return this;
      }
      public Builder addAllRole(
          java.lang.Iterable<? extends org.technbolts.protobuf.UserPBModel.Role> values) {
        if (result.role_.isEmpty()) {
          result.role_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.Role>();
        }
        super.addAll(values, result.role_);
        return this;
      }
      public Builder clearRole() {
        result.role_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.CreateRoleResponse)
    }
    
    static {
      defaultInstance = new CreateRoleResponse(true);
      org.technbolts.protobuf.RolePBCommand.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.CreateRoleResponse)
  }
  
  public static final class SearchRole extends
      com.google.protobuf.GeneratedMessage {
    // Use SearchRole.newBuilder() to construct.
    private SearchRole() {
      initFields();
    }
    private SearchRole(boolean noInit) {}
    
    private static final SearchRole defaultInstance;
    public static SearchRole getDefaultInstance() {
      return defaultInstance;
    }
    
    public SearchRole getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.RolePBCommand.internal_static_org_technbolts_protobuf_SearchRole_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.RolePBCommand.internal_static_org_technbolts_protobuf_SearchRole_fieldAccessorTable;
    }
    
    // optional .org.technbolts.protobuf.Role sample = 1;
    public static final int SAMPLE_FIELD_NUMBER = 1;
    private boolean hasSample;
    private org.technbolts.protobuf.UserPBModel.Role sample_;
    public boolean hasSample() { return hasSample; }
    public org.technbolts.protobuf.UserPBModel.Role getSample() { return sample_; }
    
    // optional .org.technbolts.protobuf.Paging paging = 2;
    public static final int PAGING_FIELD_NUMBER = 2;
    private boolean hasPaging;
    private org.technbolts.protobuf.CommonPBO.Paging paging_;
    public boolean hasPaging() { return hasPaging; }
    public org.technbolts.protobuf.CommonPBO.Paging getPaging() { return paging_; }
    
    // optional bool id_only = 3 [default = false];
    public static final int ID_ONLY_FIELD_NUMBER = 3;
    private boolean hasIdOnly;
    private boolean idOnly_ = false;
    public boolean hasIdOnly() { return hasIdOnly; }
    public boolean getIdOnly() { return idOnly_; }
    
    private void initFields() {
      sample_ = org.technbolts.protobuf.UserPBModel.Role.getDefaultInstance();
      paging_ = org.technbolts.protobuf.CommonPBO.Paging.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasSample()) {
        output.writeMessage(1, getSample());
      }
      if (hasPaging()) {
        output.writeMessage(2, getPaging());
      }
      if (hasIdOnly()) {
        output.writeBool(3, getIdOnly());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSample()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSample());
      }
      if (hasPaging()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPaging());
      }
      if (hasIdOnly()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, getIdOnly());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.RolePBCommand.SearchRole parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.SearchRole parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.SearchRole parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.SearchRole parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.SearchRole parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.SearchRole parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.SearchRole parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.RolePBCommand.SearchRole parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.RolePBCommand.SearchRole parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.SearchRole parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.RolePBCommand.SearchRole prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.RolePBCommand.SearchRole result;
      
      // Construct using org.technbolts.protobuf.RolePBCommand.SearchRole.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.RolePBCommand.SearchRole();
        return builder;
      }
      
      protected org.technbolts.protobuf.RolePBCommand.SearchRole internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.RolePBCommand.SearchRole();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.RolePBCommand.SearchRole.getDescriptor();
      }
      
      public org.technbolts.protobuf.RolePBCommand.SearchRole getDefaultInstanceForType() {
        return org.technbolts.protobuf.RolePBCommand.SearchRole.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.RolePBCommand.SearchRole build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.RolePBCommand.SearchRole buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.RolePBCommand.SearchRole buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        org.technbolts.protobuf.RolePBCommand.SearchRole returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.RolePBCommand.SearchRole) {
          return mergeFrom((org.technbolts.protobuf.RolePBCommand.SearchRole)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.RolePBCommand.SearchRole other) {
        if (other == org.technbolts.protobuf.RolePBCommand.SearchRole.getDefaultInstance()) return this;
        if (other.hasSample()) {
          mergeSample(other.getSample());
        }
        if (other.hasPaging()) {
          mergePaging(other.getPaging());
        }
        if (other.hasIdOnly()) {
          setIdOnly(other.getIdOnly());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              org.technbolts.protobuf.UserPBModel.Role.Builder subBuilder = org.technbolts.protobuf.UserPBModel.Role.newBuilder();
              if (hasSample()) {
                subBuilder.mergeFrom(getSample());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSample(subBuilder.buildPartial());
              break;
            }
            case 18: {
              org.technbolts.protobuf.CommonPBO.Paging.Builder subBuilder = org.technbolts.protobuf.CommonPBO.Paging.newBuilder();
              if (hasPaging()) {
                subBuilder.mergeFrom(getPaging());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPaging(subBuilder.buildPartial());
              break;
            }
            case 24: {
              setIdOnly(input.readBool());
              break;
            }
          }
        }
      }
      
      
      // optional .org.technbolts.protobuf.Role sample = 1;
      public boolean hasSample() {
        return result.hasSample();
      }
      public org.technbolts.protobuf.UserPBModel.Role getSample() {
        return result.getSample();
      }
      public Builder setSample(org.technbolts.protobuf.UserPBModel.Role value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasSample = true;
        result.sample_ = value;
        return this;
      }
      public Builder setSample(org.technbolts.protobuf.UserPBModel.Role.Builder builderForValue) {
        result.hasSample = true;
        result.sample_ = builderForValue.build();
        return this;
      }
      public Builder mergeSample(org.technbolts.protobuf.UserPBModel.Role value) {
        if (result.hasSample() &&
            result.sample_ != org.technbolts.protobuf.UserPBModel.Role.getDefaultInstance()) {
          result.sample_ =
            org.technbolts.protobuf.UserPBModel.Role.newBuilder(result.sample_).mergeFrom(value).buildPartial();
        } else {
          result.sample_ = value;
        }
        result.hasSample = true;
        return this;
      }
      public Builder clearSample() {
        result.hasSample = false;
        result.sample_ = org.technbolts.protobuf.UserPBModel.Role.getDefaultInstance();
        return this;
      }
      
      // optional .org.technbolts.protobuf.Paging paging = 2;
      public boolean hasPaging() {
        return result.hasPaging();
      }
      public org.technbolts.protobuf.CommonPBO.Paging getPaging() {
        return result.getPaging();
      }
      public Builder setPaging(org.technbolts.protobuf.CommonPBO.Paging value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasPaging = true;
        result.paging_ = value;
        return this;
      }
      public Builder setPaging(org.technbolts.protobuf.CommonPBO.Paging.Builder builderForValue) {
        result.hasPaging = true;
        result.paging_ = builderForValue.build();
        return this;
      }
      public Builder mergePaging(org.technbolts.protobuf.CommonPBO.Paging value) {
        if (result.hasPaging() &&
            result.paging_ != org.technbolts.protobuf.CommonPBO.Paging.getDefaultInstance()) {
          result.paging_ =
            org.technbolts.protobuf.CommonPBO.Paging.newBuilder(result.paging_).mergeFrom(value).buildPartial();
        } else {
          result.paging_ = value;
        }
        result.hasPaging = true;
        return this;
      }
      public Builder clearPaging() {
        result.hasPaging = false;
        result.paging_ = org.technbolts.protobuf.CommonPBO.Paging.getDefaultInstance();
        return this;
      }
      
      // optional bool id_only = 3 [default = false];
      public boolean hasIdOnly() {
        return result.hasIdOnly();
      }
      public boolean getIdOnly() {
        return result.getIdOnly();
      }
      public Builder setIdOnly(boolean value) {
        result.hasIdOnly = true;
        result.idOnly_ = value;
        return this;
      }
      public Builder clearIdOnly() {
        result.hasIdOnly = false;
        result.idOnly_ = false;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.SearchRole)
    }
    
    static {
      defaultInstance = new SearchRole(true);
      org.technbolts.protobuf.RolePBCommand.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.SearchRole)
  }
  
  public static final class SearchRoleResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use SearchRoleResponse.newBuilder() to construct.
    private SearchRoleResponse() {
      initFields();
    }
    private SearchRoleResponse(boolean noInit) {}
    
    private static final SearchRoleResponse defaultInstance;
    public static SearchRoleResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public SearchRoleResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.RolePBCommand.internal_static_org_technbolts_protobuf_SearchRoleResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.RolePBCommand.internal_static_org_technbolts_protobuf_SearchRoleResponse_fieldAccessorTable;
    }
    
    // repeated .org.technbolts.protobuf.Error error = 1;
    public static final int ERROR_FIELD_NUMBER = 1;
    private java.util.List<org.technbolts.protobuf.CommonPBO.Error> error_ =
      java.util.Collections.emptyList();
    public java.util.List<org.technbolts.protobuf.CommonPBO.Error> getErrorList() {
      return error_;
    }
    public int getErrorCount() { return error_.size(); }
    public org.technbolts.protobuf.CommonPBO.Error getError(int index) {
      return error_.get(index);
    }
    
    // repeated uint32 role_id = 2;
    public static final int ROLE_ID_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> roleId_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getRoleIdList() {
      return roleId_;
    }
    public int getRoleIdCount() { return roleId_.size(); }
    public int getRoleId(int index) {
      return roleId_.get(index);
    }
    
    // repeated .org.technbolts.protobuf.Role role = 3;
    public static final int ROLE_FIELD_NUMBER = 3;
    private java.util.List<org.technbolts.protobuf.UserPBModel.Role> role_ =
      java.util.Collections.emptyList();
    public java.util.List<org.technbolts.protobuf.UserPBModel.Role> getRoleList() {
      return role_;
    }
    public int getRoleCount() { return role_.size(); }
    public org.technbolts.protobuf.UserPBModel.Role getRole(int index) {
      return role_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (org.technbolts.protobuf.CommonPBO.Error element : getErrorList()) {
        output.writeMessage(1, element);
      }
      for (int element : getRoleIdList()) {
        output.writeUInt32(2, element);
      }
      for (org.technbolts.protobuf.UserPBModel.Role element : getRoleList()) {
        output.writeMessage(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (org.technbolts.protobuf.CommonPBO.Error element : getErrorList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      {
        int dataSize = 0;
        for (int element : getRoleIdList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getRoleIdList().size();
      }
      for (org.technbolts.protobuf.UserPBModel.Role element : getRoleList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.RolePBCommand.SearchRoleResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.SearchRoleResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.SearchRoleResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.SearchRoleResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.SearchRoleResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.SearchRoleResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.SearchRoleResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.RolePBCommand.SearchRoleResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.RolePBCommand.SearchRoleResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.SearchRoleResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.RolePBCommand.SearchRoleResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.RolePBCommand.SearchRoleResponse result;
      
      // Construct using org.technbolts.protobuf.RolePBCommand.SearchRoleResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.RolePBCommand.SearchRoleResponse();
        return builder;
      }
      
      protected org.technbolts.protobuf.RolePBCommand.SearchRoleResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.RolePBCommand.SearchRoleResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.RolePBCommand.SearchRoleResponse.getDescriptor();
      }
      
      public org.technbolts.protobuf.RolePBCommand.SearchRoleResponse getDefaultInstanceForType() {
        return org.technbolts.protobuf.RolePBCommand.SearchRoleResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.RolePBCommand.SearchRoleResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.RolePBCommand.SearchRoleResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.RolePBCommand.SearchRoleResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.error_ != java.util.Collections.EMPTY_LIST) {
          result.error_ =
            java.util.Collections.unmodifiableList(result.error_);
        }
        if (result.roleId_ != java.util.Collections.EMPTY_LIST) {
          result.roleId_ =
            java.util.Collections.unmodifiableList(result.roleId_);
        }
        if (result.role_ != java.util.Collections.EMPTY_LIST) {
          result.role_ =
            java.util.Collections.unmodifiableList(result.role_);
        }
        org.technbolts.protobuf.RolePBCommand.SearchRoleResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.RolePBCommand.SearchRoleResponse) {
          return mergeFrom((org.technbolts.protobuf.RolePBCommand.SearchRoleResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.RolePBCommand.SearchRoleResponse other) {
        if (other == org.technbolts.protobuf.RolePBCommand.SearchRoleResponse.getDefaultInstance()) return this;
        if (!other.error_.isEmpty()) {
          if (result.error_.isEmpty()) {
            result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
          }
          result.error_.addAll(other.error_);
        }
        if (!other.roleId_.isEmpty()) {
          if (result.roleId_.isEmpty()) {
            result.roleId_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.roleId_.addAll(other.roleId_);
        }
        if (!other.role_.isEmpty()) {
          if (result.role_.isEmpty()) {
            result.role_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.Role>();
          }
          result.role_.addAll(other.role_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              org.technbolts.protobuf.CommonPBO.Error.Builder subBuilder = org.technbolts.protobuf.CommonPBO.Error.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addError(subBuilder.buildPartial());
              break;
            }
            case 16: {
              addRoleId(input.readUInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addRoleId(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 26: {
              org.technbolts.protobuf.UserPBModel.Role.Builder subBuilder = org.technbolts.protobuf.UserPBModel.Role.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRole(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .org.technbolts.protobuf.Error error = 1;
      public java.util.List<org.technbolts.protobuf.CommonPBO.Error> getErrorList() {
        return java.util.Collections.unmodifiableList(result.error_);
      }
      public int getErrorCount() {
        return result.getErrorCount();
      }
      public org.technbolts.protobuf.CommonPBO.Error getError(int index) {
        return result.getError(index);
      }
      public Builder setError(int index, org.technbolts.protobuf.CommonPBO.Error value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.error_.set(index, value);
        return this;
      }
      public Builder setError(int index, org.technbolts.protobuf.CommonPBO.Error.Builder builderForValue) {
        result.error_.set(index, builderForValue.build());
        return this;
      }
      public Builder addError(org.technbolts.protobuf.CommonPBO.Error value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.error_.isEmpty()) {
          result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
        }
        result.error_.add(value);
        return this;
      }
      public Builder addError(org.technbolts.protobuf.CommonPBO.Error.Builder builderForValue) {
        if (result.error_.isEmpty()) {
          result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
        }
        result.error_.add(builderForValue.build());
        return this;
      }
      public Builder addAllError(
          java.lang.Iterable<? extends org.technbolts.protobuf.CommonPBO.Error> values) {
        if (result.error_.isEmpty()) {
          result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
        }
        super.addAll(values, result.error_);
        return this;
      }
      public Builder clearError() {
        result.error_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated uint32 role_id = 2;
      public java.util.List<java.lang.Integer> getRoleIdList() {
        return java.util.Collections.unmodifiableList(result.roleId_);
      }
      public int getRoleIdCount() {
        return result.getRoleIdCount();
      }
      public int getRoleId(int index) {
        return result.getRoleId(index);
      }
      public Builder setRoleId(int index, int value) {
        result.roleId_.set(index, value);
        return this;
      }
      public Builder addRoleId(int value) {
        if (result.roleId_.isEmpty()) {
          result.roleId_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.roleId_.add(value);
        return this;
      }
      public Builder addAllRoleId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.roleId_.isEmpty()) {
          result.roleId_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.roleId_);
        return this;
      }
      public Builder clearRoleId() {
        result.roleId_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .org.technbolts.protobuf.Role role = 3;
      public java.util.List<org.technbolts.protobuf.UserPBModel.Role> getRoleList() {
        return java.util.Collections.unmodifiableList(result.role_);
      }
      public int getRoleCount() {
        return result.getRoleCount();
      }
      public org.technbolts.protobuf.UserPBModel.Role getRole(int index) {
        return result.getRole(index);
      }
      public Builder setRole(int index, org.technbolts.protobuf.UserPBModel.Role value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.role_.set(index, value);
        return this;
      }
      public Builder setRole(int index, org.technbolts.protobuf.UserPBModel.Role.Builder builderForValue) {
        result.role_.set(index, builderForValue.build());
        return this;
      }
      public Builder addRole(org.technbolts.protobuf.UserPBModel.Role value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.role_.isEmpty()) {
          result.role_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.Role>();
        }
        result.role_.add(value);
        return this;
      }
      public Builder addRole(org.technbolts.protobuf.UserPBModel.Role.Builder builderForValue) {
        if (result.role_.isEmpty()) {
          result.role_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.Role>();
        }
        result.role_.add(builderForValue.build());
        return this;
      }
      public Builder addAllRole(
          java.lang.Iterable<? extends org.technbolts.protobuf.UserPBModel.Role> values) {
        if (result.role_.isEmpty()) {
          result.role_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.Role>();
        }
        super.addAll(values, result.role_);
        return this;
      }
      public Builder clearRole() {
        result.role_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.SearchRoleResponse)
    }
    
    static {
      defaultInstance = new SearchRoleResponse(true);
      org.technbolts.protobuf.RolePBCommand.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.SearchRoleResponse)
  }
  
  public static final class DeleteRole extends
      com.google.protobuf.GeneratedMessage {
    // Use DeleteRole.newBuilder() to construct.
    private DeleteRole() {
      initFields();
    }
    private DeleteRole(boolean noInit) {}
    
    private static final DeleteRole defaultInstance;
    public static DeleteRole getDefaultInstance() {
      return defaultInstance;
    }
    
    public DeleteRole getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.RolePBCommand.internal_static_org_technbolts_protobuf_DeleteRole_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.RolePBCommand.internal_static_org_technbolts_protobuf_DeleteRole_fieldAccessorTable;
    }
    
    // repeated uint32 role_id = 2;
    public static final int ROLE_ID_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> roleId_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getRoleIdList() {
      return roleId_;
    }
    public int getRoleIdCount() { return roleId_.size(); }
    public int getRoleId(int index) {
      return roleId_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int element : getRoleIdList()) {
        output.writeUInt32(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int element : getRoleIdList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getRoleIdList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.RolePBCommand.DeleteRole parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.DeleteRole parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.DeleteRole parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.DeleteRole parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.DeleteRole parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.DeleteRole parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.DeleteRole parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.RolePBCommand.DeleteRole parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.RolePBCommand.DeleteRole parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.DeleteRole parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.RolePBCommand.DeleteRole prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.RolePBCommand.DeleteRole result;
      
      // Construct using org.technbolts.protobuf.RolePBCommand.DeleteRole.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.RolePBCommand.DeleteRole();
        return builder;
      }
      
      protected org.technbolts.protobuf.RolePBCommand.DeleteRole internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.RolePBCommand.DeleteRole();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.RolePBCommand.DeleteRole.getDescriptor();
      }
      
      public org.technbolts.protobuf.RolePBCommand.DeleteRole getDefaultInstanceForType() {
        return org.technbolts.protobuf.RolePBCommand.DeleteRole.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.RolePBCommand.DeleteRole build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.RolePBCommand.DeleteRole buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.RolePBCommand.DeleteRole buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.roleId_ != java.util.Collections.EMPTY_LIST) {
          result.roleId_ =
            java.util.Collections.unmodifiableList(result.roleId_);
        }
        org.technbolts.protobuf.RolePBCommand.DeleteRole returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.RolePBCommand.DeleteRole) {
          return mergeFrom((org.technbolts.protobuf.RolePBCommand.DeleteRole)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.RolePBCommand.DeleteRole other) {
        if (other == org.technbolts.protobuf.RolePBCommand.DeleteRole.getDefaultInstance()) return this;
        if (!other.roleId_.isEmpty()) {
          if (result.roleId_.isEmpty()) {
            result.roleId_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.roleId_.addAll(other.roleId_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 16: {
              addRoleId(input.readUInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addRoleId(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // repeated uint32 role_id = 2;
      public java.util.List<java.lang.Integer> getRoleIdList() {
        return java.util.Collections.unmodifiableList(result.roleId_);
      }
      public int getRoleIdCount() {
        return result.getRoleIdCount();
      }
      public int getRoleId(int index) {
        return result.getRoleId(index);
      }
      public Builder setRoleId(int index, int value) {
        result.roleId_.set(index, value);
        return this;
      }
      public Builder addRoleId(int value) {
        if (result.roleId_.isEmpty()) {
          result.roleId_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.roleId_.add(value);
        return this;
      }
      public Builder addAllRoleId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.roleId_.isEmpty()) {
          result.roleId_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.roleId_);
        return this;
      }
      public Builder clearRoleId() {
        result.roleId_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.DeleteRole)
    }
    
    static {
      defaultInstance = new DeleteRole(true);
      org.technbolts.protobuf.RolePBCommand.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.DeleteRole)
  }
  
  public static final class DeleteRoleResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use DeleteRoleResponse.newBuilder() to construct.
    private DeleteRoleResponse() {
      initFields();
    }
    private DeleteRoleResponse(boolean noInit) {}
    
    private static final DeleteRoleResponse defaultInstance;
    public static DeleteRoleResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public DeleteRoleResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.RolePBCommand.internal_static_org_technbolts_protobuf_DeleteRoleResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.RolePBCommand.internal_static_org_technbolts_protobuf_DeleteRoleResponse_fieldAccessorTable;
    }
    
    // repeated .org.technbolts.protobuf.Error error = 1;
    public static final int ERROR_FIELD_NUMBER = 1;
    private java.util.List<org.technbolts.protobuf.CommonPBO.Error> error_ =
      java.util.Collections.emptyList();
    public java.util.List<org.technbolts.protobuf.CommonPBO.Error> getErrorList() {
      return error_;
    }
    public int getErrorCount() { return error_.size(); }
    public org.technbolts.protobuf.CommonPBO.Error getError(int index) {
      return error_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (org.technbolts.protobuf.CommonPBO.Error element : getErrorList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (org.technbolts.protobuf.CommonPBO.Error element : getErrorList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse result;
      
      // Construct using org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse();
        return builder;
      }
      
      protected org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse.getDescriptor();
      }
      
      public org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse getDefaultInstanceForType() {
        return org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.error_ != java.util.Collections.EMPTY_LIST) {
          result.error_ =
            java.util.Collections.unmodifiableList(result.error_);
        }
        org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse) {
          return mergeFrom((org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse other) {
        if (other == org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse.getDefaultInstance()) return this;
        if (!other.error_.isEmpty()) {
          if (result.error_.isEmpty()) {
            result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
          }
          result.error_.addAll(other.error_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              org.technbolts.protobuf.CommonPBO.Error.Builder subBuilder = org.technbolts.protobuf.CommonPBO.Error.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addError(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .org.technbolts.protobuf.Error error = 1;
      public java.util.List<org.technbolts.protobuf.CommonPBO.Error> getErrorList() {
        return java.util.Collections.unmodifiableList(result.error_);
      }
      public int getErrorCount() {
        return result.getErrorCount();
      }
      public org.technbolts.protobuf.CommonPBO.Error getError(int index) {
        return result.getError(index);
      }
      public Builder setError(int index, org.technbolts.protobuf.CommonPBO.Error value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.error_.set(index, value);
        return this;
      }
      public Builder setError(int index, org.technbolts.protobuf.CommonPBO.Error.Builder builderForValue) {
        result.error_.set(index, builderForValue.build());
        return this;
      }
      public Builder addError(org.technbolts.protobuf.CommonPBO.Error value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.error_.isEmpty()) {
          result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
        }
        result.error_.add(value);
        return this;
      }
      public Builder addError(org.technbolts.protobuf.CommonPBO.Error.Builder builderForValue) {
        if (result.error_.isEmpty()) {
          result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
        }
        result.error_.add(builderForValue.build());
        return this;
      }
      public Builder addAllError(
          java.lang.Iterable<? extends org.technbolts.protobuf.CommonPBO.Error> values) {
        if (result.error_.isEmpty()) {
          result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
        }
        super.addAll(values, result.error_);
        return this;
      }
      public Builder clearError() {
        result.error_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.DeleteRoleResponse)
    }
    
    static {
      defaultInstance = new DeleteRoleResponse(true);
      org.technbolts.protobuf.RolePBCommand.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.DeleteRoleResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_CreateRole_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_CreateRole_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_CreateRoleResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_CreateRoleResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_SearchRole_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_SearchRole_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_SearchRoleResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_SearchRoleResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_DeleteRole_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_DeleteRole_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_DeleteRoleResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_DeleteRoleResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023user/role-api.proto\022\027org.technbolts.pr" +
      "otobuf\032\014common.proto\032\021user/models.proto\"" +
      "Q\n\nCreateRole\022+\n\004role\030\001 \003(\0132\035.org.technb" +
      "olts.protobuf.Role\022\026\n\007id_only\030\002 \001(\010:\005fal" +
      "se\"p\n\022CreateRoleResponse\022-\n\005error\030\001 \003(\0132" +
      "\036.org.technbolts.protobuf.Error\022+\n\004role\030" +
      "\002 \003(\0132\035.org.technbolts.protobuf.Role\"\204\001\n" +
      "\nSearchRole\022-\n\006sample\030\001 \001(\0132\035.org.technb" +
      "olts.protobuf.Role\022/\n\006paging\030\002 \001(\0132\037.org" +
      ".technbolts.protobuf.Paging\022\026\n\007id_only\030\003",
      " \001(\010:\005false\"\201\001\n\022SearchRoleResponse\022-\n\005er" +
      "ror\030\001 \003(\0132\036.org.technbolts.protobuf.Erro" +
      "r\022\017\n\007role_id\030\002 \003(\r\022+\n\004role\030\003 \003(\0132\035.org.t" +
      "echnbolts.protobuf.Role\"\035\n\nDeleteRole\022\017\n" +
      "\007role_id\030\002 \003(\r\"C\n\022DeleteRoleResponse\022-\n\005" +
      "error\030\001 \003(\0132\036.org.technbolts.protobuf.Er" +
      "rorB*\n\027org.technbolts.protobufB\rRolePBCo" +
      "mmandH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_technbolts_protobuf_CreateRole_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_technbolts_protobuf_CreateRole_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_CreateRole_descriptor,
              new java.lang.String[] { "Role", "IdOnly", },
              org.technbolts.protobuf.RolePBCommand.CreateRole.class,
              org.technbolts.protobuf.RolePBCommand.CreateRole.Builder.class);
          internal_static_org_technbolts_protobuf_CreateRoleResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_technbolts_protobuf_CreateRoleResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_CreateRoleResponse_descriptor,
              new java.lang.String[] { "Error", "Role", },
              org.technbolts.protobuf.RolePBCommand.CreateRoleResponse.class,
              org.technbolts.protobuf.RolePBCommand.CreateRoleResponse.Builder.class);
          internal_static_org_technbolts_protobuf_SearchRole_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_org_technbolts_protobuf_SearchRole_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_SearchRole_descriptor,
              new java.lang.String[] { "Sample", "Paging", "IdOnly", },
              org.technbolts.protobuf.RolePBCommand.SearchRole.class,
              org.technbolts.protobuf.RolePBCommand.SearchRole.Builder.class);
          internal_static_org_technbolts_protobuf_SearchRoleResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_org_technbolts_protobuf_SearchRoleResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_SearchRoleResponse_descriptor,
              new java.lang.String[] { "Error", "RoleId", "Role", },
              org.technbolts.protobuf.RolePBCommand.SearchRoleResponse.class,
              org.technbolts.protobuf.RolePBCommand.SearchRoleResponse.Builder.class);
          internal_static_org_technbolts_protobuf_DeleteRole_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_org_technbolts_protobuf_DeleteRole_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_DeleteRole_descriptor,
              new java.lang.String[] { "RoleId", },
              org.technbolts.protobuf.RolePBCommand.DeleteRole.class,
              org.technbolts.protobuf.RolePBCommand.DeleteRole.Builder.class);
          internal_static_org_technbolts_protobuf_DeleteRoleResponse_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_org_technbolts_protobuf_DeleteRoleResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_DeleteRoleResponse_descriptor,
              new java.lang.String[] { "Error", },
              org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse.class,
              org.technbolts.protobuf.RolePBCommand.DeleteRoleResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.technbolts.protobuf.CommonPBO.getDescriptor(),
          org.technbolts.protobuf.UserPBModel.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
