// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package org.technbolts.protobuf;

public final class UserPBO {
  private UserPBO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class User extends
      com.google.protobuf.GeneratedMessage {
    // Use User.newBuilder() to construct.
    private User() {
      initFields();
    }
    private User(boolean noInit) {}
    
    private static final User defaultInstance;
    public static User getDefaultInstance() {
      return defaultInstance;
    }
    
    public User getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.UserPBO.internal_static_org_technbolts_protobuf_User_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.UserPBO.internal_static_org_technbolts_protobuf_User_fieldAccessorTable;
    }
    
    // optional uint32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional string nickname = 2;
    public static final int NICKNAME_FIELD_NUMBER = 2;
    private boolean hasNickname;
    private java.lang.String nickname_ = "";
    public boolean hasNickname() { return hasNickname; }
    public java.lang.String getNickname() { return nickname_; }
    
    // optional string firstname = 3;
    public static final int FIRSTNAME_FIELD_NUMBER = 3;
    private boolean hasFirstname;
    private java.lang.String firstname_ = "";
    public boolean hasFirstname() { return hasFirstname; }
    public java.lang.String getFirstname() { return firstname_; }
    
    // optional string lastname = 4;
    public static final int LASTNAME_FIELD_NUMBER = 4;
    private boolean hasLastname;
    private java.lang.String lastname_ = "";
    public boolean hasLastname() { return hasLastname; }
    public java.lang.String getLastname() { return lastname_; }
    
    // optional string email = 5;
    public static final int EMAIL_FIELD_NUMBER = 5;
    private boolean hasEmail;
    private java.lang.String email_ = "";
    public boolean hasEmail() { return hasEmail; }
    public java.lang.String getEmail() { return email_; }
    
    // optional .org.technbolts.protobuf.EntityDescriptor entity_descriptor = 6;
    public static final int ENTITY_DESCRIPTOR_FIELD_NUMBER = 6;
    private boolean hasEntityDescriptor;
    private org.technbolts.protobuf.CommonPBO.EntityDescriptor entityDescriptor_;
    public boolean hasEntityDescriptor() { return hasEntityDescriptor; }
    public org.technbolts.protobuf.CommonPBO.EntityDescriptor getEntityDescriptor() { return entityDescriptor_; }
    
    // repeated .org.technbolts.protobuf.PropertyValue property = 7;
    public static final int PROPERTY_FIELD_NUMBER = 7;
    private java.util.List<org.technbolts.protobuf.CommonPBO.PropertyValue> property_ =
      java.util.Collections.emptyList();
    public java.util.List<org.technbolts.protobuf.CommonPBO.PropertyValue> getPropertyList() {
      return property_;
    }
    public int getPropertyCount() { return property_.size(); }
    public org.technbolts.protobuf.CommonPBO.PropertyValue getProperty(int index) {
      return property_.get(index);
    }
    
    private void initFields() {
      entityDescriptor_ = org.technbolts.protobuf.CommonPBO.EntityDescriptor.getDefaultInstance();
    }
    public final boolean isInitialized() {
      for (org.technbolts.protobuf.CommonPBO.PropertyValue element : getPropertyList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeUInt32(1, getId());
      }
      if (hasNickname()) {
        output.writeString(2, getNickname());
      }
      if (hasFirstname()) {
        output.writeString(3, getFirstname());
      }
      if (hasLastname()) {
        output.writeString(4, getLastname());
      }
      if (hasEmail()) {
        output.writeString(5, getEmail());
      }
      if (hasEntityDescriptor()) {
        output.writeMessage(6, getEntityDescriptor());
      }
      for (org.technbolts.protobuf.CommonPBO.PropertyValue element : getPropertyList()) {
        output.writeMessage(7, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, getId());
      }
      if (hasNickname()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getNickname());
      }
      if (hasFirstname()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getFirstname());
      }
      if (hasLastname()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getLastname());
      }
      if (hasEmail()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getEmail());
      }
      if (hasEntityDescriptor()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getEntityDescriptor());
      }
      for (org.technbolts.protobuf.CommonPBO.PropertyValue element : getPropertyList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.UserPBO.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBO.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBO.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBO.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBO.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBO.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBO.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.UserPBO.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.UserPBO.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBO.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.UserPBO.User prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.UserPBO.User result;
      
      // Construct using org.technbolts.protobuf.UserPBO.User.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.UserPBO.User();
        return builder;
      }
      
      protected org.technbolts.protobuf.UserPBO.User internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.UserPBO.User();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.UserPBO.User.getDescriptor();
      }
      
      public org.technbolts.protobuf.UserPBO.User getDefaultInstanceForType() {
        return org.technbolts.protobuf.UserPBO.User.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.UserPBO.User build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.UserPBO.User buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.UserPBO.User buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.property_ != java.util.Collections.EMPTY_LIST) {
          result.property_ =
            java.util.Collections.unmodifiableList(result.property_);
        }
        org.technbolts.protobuf.UserPBO.User returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.UserPBO.User) {
          return mergeFrom((org.technbolts.protobuf.UserPBO.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.UserPBO.User other) {
        if (other == org.technbolts.protobuf.UserPBO.User.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasNickname()) {
          setNickname(other.getNickname());
        }
        if (other.hasFirstname()) {
          setFirstname(other.getFirstname());
        }
        if (other.hasLastname()) {
          setLastname(other.getLastname());
        }
        if (other.hasEmail()) {
          setEmail(other.getEmail());
        }
        if (other.hasEntityDescriptor()) {
          mergeEntityDescriptor(other.getEntityDescriptor());
        }
        if (!other.property_.isEmpty()) {
          if (result.property_.isEmpty()) {
            result.property_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.PropertyValue>();
          }
          result.property_.addAll(other.property_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readUInt32());
              break;
            }
            case 18: {
              setNickname(input.readString());
              break;
            }
            case 26: {
              setFirstname(input.readString());
              break;
            }
            case 34: {
              setLastname(input.readString());
              break;
            }
            case 42: {
              setEmail(input.readString());
              break;
            }
            case 50: {
              org.technbolts.protobuf.CommonPBO.EntityDescriptor.Builder subBuilder = org.technbolts.protobuf.CommonPBO.EntityDescriptor.newBuilder();
              if (hasEntityDescriptor()) {
                subBuilder.mergeFrom(getEntityDescriptor());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setEntityDescriptor(subBuilder.buildPartial());
              break;
            }
            case 58: {
              org.technbolts.protobuf.CommonPBO.PropertyValue.Builder subBuilder = org.technbolts.protobuf.CommonPBO.PropertyValue.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addProperty(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional uint32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional string nickname = 2;
      public boolean hasNickname() {
        return result.hasNickname();
      }
      public java.lang.String getNickname() {
        return result.getNickname();
      }
      public Builder setNickname(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasNickname = true;
        result.nickname_ = value;
        return this;
      }
      public Builder clearNickname() {
        result.hasNickname = false;
        result.nickname_ = getDefaultInstance().getNickname();
        return this;
      }
      
      // optional string firstname = 3;
      public boolean hasFirstname() {
        return result.hasFirstname();
      }
      public java.lang.String getFirstname() {
        return result.getFirstname();
      }
      public Builder setFirstname(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasFirstname = true;
        result.firstname_ = value;
        return this;
      }
      public Builder clearFirstname() {
        result.hasFirstname = false;
        result.firstname_ = getDefaultInstance().getFirstname();
        return this;
      }
      
      // optional string lastname = 4;
      public boolean hasLastname() {
        return result.hasLastname();
      }
      public java.lang.String getLastname() {
        return result.getLastname();
      }
      public Builder setLastname(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLastname = true;
        result.lastname_ = value;
        return this;
      }
      public Builder clearLastname() {
        result.hasLastname = false;
        result.lastname_ = getDefaultInstance().getLastname();
        return this;
      }
      
      // optional string email = 5;
      public boolean hasEmail() {
        return result.hasEmail();
      }
      public java.lang.String getEmail() {
        return result.getEmail();
      }
      public Builder setEmail(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasEmail = true;
        result.email_ = value;
        return this;
      }
      public Builder clearEmail() {
        result.hasEmail = false;
        result.email_ = getDefaultInstance().getEmail();
        return this;
      }
      
      // optional .org.technbolts.protobuf.EntityDescriptor entity_descriptor = 6;
      public boolean hasEntityDescriptor() {
        return result.hasEntityDescriptor();
      }
      public org.technbolts.protobuf.CommonPBO.EntityDescriptor getEntityDescriptor() {
        return result.getEntityDescriptor();
      }
      public Builder setEntityDescriptor(org.technbolts.protobuf.CommonPBO.EntityDescriptor value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasEntityDescriptor = true;
        result.entityDescriptor_ = value;
        return this;
      }
      public Builder setEntityDescriptor(org.technbolts.protobuf.CommonPBO.EntityDescriptor.Builder builderForValue) {
        result.hasEntityDescriptor = true;
        result.entityDescriptor_ = builderForValue.build();
        return this;
      }
      public Builder mergeEntityDescriptor(org.technbolts.protobuf.CommonPBO.EntityDescriptor value) {
        if (result.hasEntityDescriptor() &&
            result.entityDescriptor_ != org.technbolts.protobuf.CommonPBO.EntityDescriptor.getDefaultInstance()) {
          result.entityDescriptor_ =
            org.technbolts.protobuf.CommonPBO.EntityDescriptor.newBuilder(result.entityDescriptor_).mergeFrom(value).buildPartial();
        } else {
          result.entityDescriptor_ = value;
        }
        result.hasEntityDescriptor = true;
        return this;
      }
      public Builder clearEntityDescriptor() {
        result.hasEntityDescriptor = false;
        result.entityDescriptor_ = org.technbolts.protobuf.CommonPBO.EntityDescriptor.getDefaultInstance();
        return this;
      }
      
      // repeated .org.technbolts.protobuf.PropertyValue property = 7;
      public java.util.List<org.technbolts.protobuf.CommonPBO.PropertyValue> getPropertyList() {
        return java.util.Collections.unmodifiableList(result.property_);
      }
      public int getPropertyCount() {
        return result.getPropertyCount();
      }
      public org.technbolts.protobuf.CommonPBO.PropertyValue getProperty(int index) {
        return result.getProperty(index);
      }
      public Builder setProperty(int index, org.technbolts.protobuf.CommonPBO.PropertyValue value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.property_.set(index, value);
        return this;
      }
      public Builder setProperty(int index, org.technbolts.protobuf.CommonPBO.PropertyValue.Builder builderForValue) {
        result.property_.set(index, builderForValue.build());
        return this;
      }
      public Builder addProperty(org.technbolts.protobuf.CommonPBO.PropertyValue value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.property_.isEmpty()) {
          result.property_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.PropertyValue>();
        }
        result.property_.add(value);
        return this;
      }
      public Builder addProperty(org.technbolts.protobuf.CommonPBO.PropertyValue.Builder builderForValue) {
        if (result.property_.isEmpty()) {
          result.property_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.PropertyValue>();
        }
        result.property_.add(builderForValue.build());
        return this;
      }
      public Builder addAllProperty(
          java.lang.Iterable<? extends org.technbolts.protobuf.CommonPBO.PropertyValue> values) {
        if (result.property_.isEmpty()) {
          result.property_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.PropertyValue>();
        }
        super.addAll(values, result.property_);
        return this;
      }
      public Builder clearProperty() {
        result.property_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.User)
    }
    
    static {
      defaultInstance = new User(true);
      org.technbolts.protobuf.UserPBO.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.User)
  }
  
  public static final class CreateUser extends
      com.google.protobuf.GeneratedMessage {
    // Use CreateUser.newBuilder() to construct.
    private CreateUser() {
      initFields();
    }
    private CreateUser(boolean noInit) {}
    
    private static final CreateUser defaultInstance;
    public static CreateUser getDefaultInstance() {
      return defaultInstance;
    }
    
    public CreateUser getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.UserPBO.internal_static_org_technbolts_protobuf_CreateUser_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.UserPBO.internal_static_org_technbolts_protobuf_CreateUser_fieldAccessorTable;
    }
    
    // repeated .org.technbolts.protobuf.User user = 1;
    public static final int USER_FIELD_NUMBER = 1;
    private java.util.List<org.technbolts.protobuf.UserPBO.User> user_ =
      java.util.Collections.emptyList();
    public java.util.List<org.technbolts.protobuf.UserPBO.User> getUserList() {
      return user_;
    }
    public int getUserCount() { return user_.size(); }
    public org.technbolts.protobuf.UserPBO.User getUser(int index) {
      return user_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      for (org.technbolts.protobuf.UserPBO.User element : getUserList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (org.technbolts.protobuf.UserPBO.User element : getUserList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (org.technbolts.protobuf.UserPBO.User element : getUserList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.UserPBO.CreateUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBO.CreateUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBO.CreateUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBO.CreateUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBO.CreateUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBO.CreateUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBO.CreateUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.UserPBO.CreateUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.UserPBO.CreateUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBO.CreateUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.UserPBO.CreateUser prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.UserPBO.CreateUser result;
      
      // Construct using org.technbolts.protobuf.UserPBO.CreateUser.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.UserPBO.CreateUser();
        return builder;
      }
      
      protected org.technbolts.protobuf.UserPBO.CreateUser internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.UserPBO.CreateUser();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.UserPBO.CreateUser.getDescriptor();
      }
      
      public org.technbolts.protobuf.UserPBO.CreateUser getDefaultInstanceForType() {
        return org.technbolts.protobuf.UserPBO.CreateUser.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.UserPBO.CreateUser build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.UserPBO.CreateUser buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.UserPBO.CreateUser buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.user_ != java.util.Collections.EMPTY_LIST) {
          result.user_ =
            java.util.Collections.unmodifiableList(result.user_);
        }
        org.technbolts.protobuf.UserPBO.CreateUser returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.UserPBO.CreateUser) {
          return mergeFrom((org.technbolts.protobuf.UserPBO.CreateUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.UserPBO.CreateUser other) {
        if (other == org.technbolts.protobuf.UserPBO.CreateUser.getDefaultInstance()) return this;
        if (!other.user_.isEmpty()) {
          if (result.user_.isEmpty()) {
            result.user_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBO.User>();
          }
          result.user_.addAll(other.user_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              org.technbolts.protobuf.UserPBO.User.Builder subBuilder = org.technbolts.protobuf.UserPBO.User.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addUser(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .org.technbolts.protobuf.User user = 1;
      public java.util.List<org.technbolts.protobuf.UserPBO.User> getUserList() {
        return java.util.Collections.unmodifiableList(result.user_);
      }
      public int getUserCount() {
        return result.getUserCount();
      }
      public org.technbolts.protobuf.UserPBO.User getUser(int index) {
        return result.getUser(index);
      }
      public Builder setUser(int index, org.technbolts.protobuf.UserPBO.User value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.user_.set(index, value);
        return this;
      }
      public Builder setUser(int index, org.technbolts.protobuf.UserPBO.User.Builder builderForValue) {
        result.user_.set(index, builderForValue.build());
        return this;
      }
      public Builder addUser(org.technbolts.protobuf.UserPBO.User value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.user_.isEmpty()) {
          result.user_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBO.User>();
        }
        result.user_.add(value);
        return this;
      }
      public Builder addUser(org.technbolts.protobuf.UserPBO.User.Builder builderForValue) {
        if (result.user_.isEmpty()) {
          result.user_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBO.User>();
        }
        result.user_.add(builderForValue.build());
        return this;
      }
      public Builder addAllUser(
          java.lang.Iterable<? extends org.technbolts.protobuf.UserPBO.User> values) {
        if (result.user_.isEmpty()) {
          result.user_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBO.User>();
        }
        super.addAll(values, result.user_);
        return this;
      }
      public Builder clearUser() {
        result.user_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.CreateUser)
    }
    
    static {
      defaultInstance = new CreateUser(true);
      org.technbolts.protobuf.UserPBO.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.CreateUser)
  }
  
  public static final class SearchUser extends
      com.google.protobuf.GeneratedMessage {
    // Use SearchUser.newBuilder() to construct.
    private SearchUser() {
      initFields();
    }
    private SearchUser(boolean noInit) {}
    
    private static final SearchUser defaultInstance;
    public static SearchUser getDefaultInstance() {
      return defaultInstance;
    }
    
    public SearchUser getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.UserPBO.internal_static_org_technbolts_protobuf_SearchUser_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.UserPBO.internal_static_org_technbolts_protobuf_SearchUser_fieldAccessorTable;
    }
    
    // optional .org.technbolts.protobuf.User sample = 1;
    public static final int SAMPLE_FIELD_NUMBER = 1;
    private boolean hasSample;
    private org.technbolts.protobuf.UserPBO.User sample_;
    public boolean hasSample() { return hasSample; }
    public org.technbolts.protobuf.UserPBO.User getSample() { return sample_; }
    
    // optional .org.technbolts.protobuf.Paging paging = 2;
    public static final int PAGING_FIELD_NUMBER = 2;
    private boolean hasPaging;
    private org.technbolts.protobuf.CommonPBO.Paging paging_;
    public boolean hasPaging() { return hasPaging; }
    public org.technbolts.protobuf.CommonPBO.Paging getPaging() { return paging_; }
    
    private void initFields() {
      sample_ = org.technbolts.protobuf.UserPBO.User.getDefaultInstance();
      paging_ = org.technbolts.protobuf.CommonPBO.Paging.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (hasSample()) {
        if (!getSample().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasSample()) {
        output.writeMessage(1, getSample());
      }
      if (hasPaging()) {
        output.writeMessage(2, getPaging());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSample()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSample());
      }
      if (hasPaging()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPaging());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.UserPBO.SearchUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBO.SearchUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBO.SearchUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBO.SearchUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBO.SearchUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBO.SearchUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBO.SearchUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.UserPBO.SearchUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.UserPBO.SearchUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBO.SearchUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.UserPBO.SearchUser prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.UserPBO.SearchUser result;
      
      // Construct using org.technbolts.protobuf.UserPBO.SearchUser.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.UserPBO.SearchUser();
        return builder;
      }
      
      protected org.technbolts.protobuf.UserPBO.SearchUser internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.UserPBO.SearchUser();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.UserPBO.SearchUser.getDescriptor();
      }
      
      public org.technbolts.protobuf.UserPBO.SearchUser getDefaultInstanceForType() {
        return org.technbolts.protobuf.UserPBO.SearchUser.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.UserPBO.SearchUser build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.UserPBO.SearchUser buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.UserPBO.SearchUser buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        org.technbolts.protobuf.UserPBO.SearchUser returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.UserPBO.SearchUser) {
          return mergeFrom((org.technbolts.protobuf.UserPBO.SearchUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.UserPBO.SearchUser other) {
        if (other == org.technbolts.protobuf.UserPBO.SearchUser.getDefaultInstance()) return this;
        if (other.hasSample()) {
          mergeSample(other.getSample());
        }
        if (other.hasPaging()) {
          mergePaging(other.getPaging());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              org.technbolts.protobuf.UserPBO.User.Builder subBuilder = org.technbolts.protobuf.UserPBO.User.newBuilder();
              if (hasSample()) {
                subBuilder.mergeFrom(getSample());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSample(subBuilder.buildPartial());
              break;
            }
            case 18: {
              org.technbolts.protobuf.CommonPBO.Paging.Builder subBuilder = org.technbolts.protobuf.CommonPBO.Paging.newBuilder();
              if (hasPaging()) {
                subBuilder.mergeFrom(getPaging());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPaging(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .org.technbolts.protobuf.User sample = 1;
      public boolean hasSample() {
        return result.hasSample();
      }
      public org.technbolts.protobuf.UserPBO.User getSample() {
        return result.getSample();
      }
      public Builder setSample(org.technbolts.protobuf.UserPBO.User value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasSample = true;
        result.sample_ = value;
        return this;
      }
      public Builder setSample(org.technbolts.protobuf.UserPBO.User.Builder builderForValue) {
        result.hasSample = true;
        result.sample_ = builderForValue.build();
        return this;
      }
      public Builder mergeSample(org.technbolts.protobuf.UserPBO.User value) {
        if (result.hasSample() &&
            result.sample_ != org.technbolts.protobuf.UserPBO.User.getDefaultInstance()) {
          result.sample_ =
            org.technbolts.protobuf.UserPBO.User.newBuilder(result.sample_).mergeFrom(value).buildPartial();
        } else {
          result.sample_ = value;
        }
        result.hasSample = true;
        return this;
      }
      public Builder clearSample() {
        result.hasSample = false;
        result.sample_ = org.technbolts.protobuf.UserPBO.User.getDefaultInstance();
        return this;
      }
      
      // optional .org.technbolts.protobuf.Paging paging = 2;
      public boolean hasPaging() {
        return result.hasPaging();
      }
      public org.technbolts.protobuf.CommonPBO.Paging getPaging() {
        return result.getPaging();
      }
      public Builder setPaging(org.technbolts.protobuf.CommonPBO.Paging value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasPaging = true;
        result.paging_ = value;
        return this;
      }
      public Builder setPaging(org.technbolts.protobuf.CommonPBO.Paging.Builder builderForValue) {
        result.hasPaging = true;
        result.paging_ = builderForValue.build();
        return this;
      }
      public Builder mergePaging(org.technbolts.protobuf.CommonPBO.Paging value) {
        if (result.hasPaging() &&
            result.paging_ != org.technbolts.protobuf.CommonPBO.Paging.getDefaultInstance()) {
          result.paging_ =
            org.technbolts.protobuf.CommonPBO.Paging.newBuilder(result.paging_).mergeFrom(value).buildPartial();
        } else {
          result.paging_ = value;
        }
        result.hasPaging = true;
        return this;
      }
      public Builder clearPaging() {
        result.hasPaging = false;
        result.paging_ = org.technbolts.protobuf.CommonPBO.Paging.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.SearchUser)
    }
    
    static {
      defaultInstance = new SearchUser(true);
      org.technbolts.protobuf.UserPBO.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.SearchUser)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_User_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_CreateUser_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_CreateUser_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_SearchUser_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_SearchUser_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\027org.technbolts.protobuf\032\014c" +
      "ommon.proto\"\330\001\n\004User\022\n\n\002id\030\001 \001(\r\022\020\n\010nick" +
      "name\030\002 \001(\t\022\021\n\tfirstname\030\003 \001(\t\022\020\n\010lastnam" +
      "e\030\004 \001(\t\022\r\n\005email\030\005 \001(\t\022D\n\021entity_descrip" +
      "tor\030\006 \001(\0132).org.technbolts.protobuf.Enti" +
      "tyDescriptor\0228\n\010property\030\007 \003(\0132&.org.tec" +
      "hnbolts.protobuf.PropertyValue\"9\n\nCreate" +
      "User\022+\n\004user\030\001 \003(\0132\035.org.technbolts.prot" +
      "obuf.User\"l\n\nSearchUser\022-\n\006sample\030\001 \001(\0132" +
      "\035.org.technbolts.protobuf.User\022/\n\006paging",
      "\030\002 \001(\0132\037.org.technbolts.protobuf.PagingB" +
      "$\n\027org.technbolts.protobufB\007UserPBOH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_technbolts_protobuf_User_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_technbolts_protobuf_User_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_User_descriptor,
              new java.lang.String[] { "Id", "Nickname", "Firstname", "Lastname", "Email", "EntityDescriptor", "Property", },
              org.technbolts.protobuf.UserPBO.User.class,
              org.technbolts.protobuf.UserPBO.User.Builder.class);
          internal_static_org_technbolts_protobuf_CreateUser_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_technbolts_protobuf_CreateUser_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_CreateUser_descriptor,
              new java.lang.String[] { "User", },
              org.technbolts.protobuf.UserPBO.CreateUser.class,
              org.technbolts.protobuf.UserPBO.CreateUser.Builder.class);
          internal_static_org_technbolts_protobuf_SearchUser_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_org_technbolts_protobuf_SearchUser_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_SearchUser_descriptor,
              new java.lang.String[] { "Sample", "Paging", },
              org.technbolts.protobuf.UserPBO.SearchUser.class,
              org.technbolts.protobuf.UserPBO.SearchUser.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.technbolts.protobuf.CommonPBO.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
