// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/user-api.proto

package org.technbolts.protobuf;

public final class UserPBCommand {
  private UserPBCommand() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CreateUser extends
      com.google.protobuf.GeneratedMessage {
    // Use CreateUser.newBuilder() to construct.
    private CreateUser() {
      initFields();
    }
    private CreateUser(boolean noInit) {}
    
    private static final CreateUser defaultInstance;
    public static CreateUser getDefaultInstance() {
      return defaultInstance;
    }
    
    public CreateUser getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.UserPBCommand.internal_static_org_technbolts_protobuf_CreateUser_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.UserPBCommand.internal_static_org_technbolts_protobuf_CreateUser_fieldAccessorTable;
    }
    
    // repeated .org.technbolts.protobuf.User user = 1;
    public static final int USER_FIELD_NUMBER = 1;
    private java.util.List<org.technbolts.protobuf.UserPBModel.User> user_ =
      java.util.Collections.emptyList();
    public java.util.List<org.technbolts.protobuf.UserPBModel.User> getUserList() {
      return user_;
    }
    public int getUserCount() { return user_.size(); }
    public org.technbolts.protobuf.UserPBModel.User getUser(int index) {
      return user_.get(index);
    }
    
    // optional bool id_only = 2 [default = false];
    public static final int ID_ONLY_FIELD_NUMBER = 2;
    private boolean hasIdOnly;
    private boolean idOnly_ = false;
    public boolean hasIdOnly() { return hasIdOnly; }
    public boolean getIdOnly() { return idOnly_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      for (org.technbolts.protobuf.UserPBModel.User element : getUserList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (org.technbolts.protobuf.UserPBModel.User element : getUserList()) {
        output.writeMessage(1, element);
      }
      if (hasIdOnly()) {
        output.writeBool(2, getIdOnly());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (org.technbolts.protobuf.UserPBModel.User element : getUserList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      if (hasIdOnly()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, getIdOnly());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.UserPBCommand.CreateUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.CreateUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.CreateUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.CreateUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.CreateUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.CreateUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.CreateUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.UserPBCommand.CreateUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.UserPBCommand.CreateUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.CreateUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.UserPBCommand.CreateUser prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.UserPBCommand.CreateUser result;
      
      // Construct using org.technbolts.protobuf.UserPBCommand.CreateUser.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.UserPBCommand.CreateUser();
        return builder;
      }
      
      protected org.technbolts.protobuf.UserPBCommand.CreateUser internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.UserPBCommand.CreateUser();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.UserPBCommand.CreateUser.getDescriptor();
      }
      
      public org.technbolts.protobuf.UserPBCommand.CreateUser getDefaultInstanceForType() {
        return org.technbolts.protobuf.UserPBCommand.CreateUser.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.UserPBCommand.CreateUser build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.UserPBCommand.CreateUser buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.UserPBCommand.CreateUser buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.user_ != java.util.Collections.EMPTY_LIST) {
          result.user_ =
            java.util.Collections.unmodifiableList(result.user_);
        }
        org.technbolts.protobuf.UserPBCommand.CreateUser returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.UserPBCommand.CreateUser) {
          return mergeFrom((org.technbolts.protobuf.UserPBCommand.CreateUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.UserPBCommand.CreateUser other) {
        if (other == org.technbolts.protobuf.UserPBCommand.CreateUser.getDefaultInstance()) return this;
        if (!other.user_.isEmpty()) {
          if (result.user_.isEmpty()) {
            result.user_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.User>();
          }
          result.user_.addAll(other.user_);
        }
        if (other.hasIdOnly()) {
          setIdOnly(other.getIdOnly());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              org.technbolts.protobuf.UserPBModel.User.Builder subBuilder = org.technbolts.protobuf.UserPBModel.User.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addUser(subBuilder.buildPartial());
              break;
            }
            case 16: {
              setIdOnly(input.readBool());
              break;
            }
          }
        }
      }
      
      
      // repeated .org.technbolts.protobuf.User user = 1;
      public java.util.List<org.technbolts.protobuf.UserPBModel.User> getUserList() {
        return java.util.Collections.unmodifiableList(result.user_);
      }
      public int getUserCount() {
        return result.getUserCount();
      }
      public org.technbolts.protobuf.UserPBModel.User getUser(int index) {
        return result.getUser(index);
      }
      public Builder setUser(int index, org.technbolts.protobuf.UserPBModel.User value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.user_.set(index, value);
        return this;
      }
      public Builder setUser(int index, org.technbolts.protobuf.UserPBModel.User.Builder builderForValue) {
        result.user_.set(index, builderForValue.build());
        return this;
      }
      public Builder addUser(org.technbolts.protobuf.UserPBModel.User value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.user_.isEmpty()) {
          result.user_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.User>();
        }
        result.user_.add(value);
        return this;
      }
      public Builder addUser(org.technbolts.protobuf.UserPBModel.User.Builder builderForValue) {
        if (result.user_.isEmpty()) {
          result.user_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.User>();
        }
        result.user_.add(builderForValue.build());
        return this;
      }
      public Builder addAllUser(
          java.lang.Iterable<? extends org.technbolts.protobuf.UserPBModel.User> values) {
        if (result.user_.isEmpty()) {
          result.user_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.User>();
        }
        super.addAll(values, result.user_);
        return this;
      }
      public Builder clearUser() {
        result.user_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional bool id_only = 2 [default = false];
      public boolean hasIdOnly() {
        return result.hasIdOnly();
      }
      public boolean getIdOnly() {
        return result.getIdOnly();
      }
      public Builder setIdOnly(boolean value) {
        result.hasIdOnly = true;
        result.idOnly_ = value;
        return this;
      }
      public Builder clearIdOnly() {
        result.hasIdOnly = false;
        result.idOnly_ = false;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.CreateUser)
    }
    
    static {
      defaultInstance = new CreateUser(true);
      org.technbolts.protobuf.UserPBCommand.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.CreateUser)
  }
  
  public static final class CreateUserResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use CreateUserResponse.newBuilder() to construct.
    private CreateUserResponse() {
      initFields();
    }
    private CreateUserResponse(boolean noInit) {}
    
    private static final CreateUserResponse defaultInstance;
    public static CreateUserResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public CreateUserResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.UserPBCommand.internal_static_org_technbolts_protobuf_CreateUserResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.UserPBCommand.internal_static_org_technbolts_protobuf_CreateUserResponse_fieldAccessorTable;
    }
    
    // repeated .org.technbolts.protobuf.Error error = 1;
    public static final int ERROR_FIELD_NUMBER = 1;
    private java.util.List<org.technbolts.protobuf.CommonPBO.Error> error_ =
      java.util.Collections.emptyList();
    public java.util.List<org.technbolts.protobuf.CommonPBO.Error> getErrorList() {
      return error_;
    }
    public int getErrorCount() { return error_.size(); }
    public org.technbolts.protobuf.CommonPBO.Error getError(int index) {
      return error_.get(index);
    }
    
    // repeated .org.technbolts.protobuf.User user = 2;
    public static final int USER_FIELD_NUMBER = 2;
    private java.util.List<org.technbolts.protobuf.UserPBModel.User> user_ =
      java.util.Collections.emptyList();
    public java.util.List<org.technbolts.protobuf.UserPBModel.User> getUserList() {
      return user_;
    }
    public int getUserCount() { return user_.size(); }
    public org.technbolts.protobuf.UserPBModel.User getUser(int index) {
      return user_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      for (org.technbolts.protobuf.UserPBModel.User element : getUserList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (org.technbolts.protobuf.CommonPBO.Error element : getErrorList()) {
        output.writeMessage(1, element);
      }
      for (org.technbolts.protobuf.UserPBModel.User element : getUserList()) {
        output.writeMessage(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (org.technbolts.protobuf.CommonPBO.Error element : getErrorList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      for (org.technbolts.protobuf.UserPBModel.User element : getUserList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.UserPBCommand.CreateUserResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.CreateUserResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.CreateUserResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.CreateUserResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.CreateUserResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.CreateUserResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.CreateUserResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.UserPBCommand.CreateUserResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.UserPBCommand.CreateUserResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.CreateUserResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.UserPBCommand.CreateUserResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.UserPBCommand.CreateUserResponse result;
      
      // Construct using org.technbolts.protobuf.UserPBCommand.CreateUserResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.UserPBCommand.CreateUserResponse();
        return builder;
      }
      
      protected org.technbolts.protobuf.UserPBCommand.CreateUserResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.UserPBCommand.CreateUserResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.UserPBCommand.CreateUserResponse.getDescriptor();
      }
      
      public org.technbolts.protobuf.UserPBCommand.CreateUserResponse getDefaultInstanceForType() {
        return org.technbolts.protobuf.UserPBCommand.CreateUserResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.UserPBCommand.CreateUserResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.UserPBCommand.CreateUserResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.UserPBCommand.CreateUserResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.error_ != java.util.Collections.EMPTY_LIST) {
          result.error_ =
            java.util.Collections.unmodifiableList(result.error_);
        }
        if (result.user_ != java.util.Collections.EMPTY_LIST) {
          result.user_ =
            java.util.Collections.unmodifiableList(result.user_);
        }
        org.technbolts.protobuf.UserPBCommand.CreateUserResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.UserPBCommand.CreateUserResponse) {
          return mergeFrom((org.technbolts.protobuf.UserPBCommand.CreateUserResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.UserPBCommand.CreateUserResponse other) {
        if (other == org.technbolts.protobuf.UserPBCommand.CreateUserResponse.getDefaultInstance()) return this;
        if (!other.error_.isEmpty()) {
          if (result.error_.isEmpty()) {
            result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
          }
          result.error_.addAll(other.error_);
        }
        if (!other.user_.isEmpty()) {
          if (result.user_.isEmpty()) {
            result.user_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.User>();
          }
          result.user_.addAll(other.user_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              org.technbolts.protobuf.CommonPBO.Error.Builder subBuilder = org.technbolts.protobuf.CommonPBO.Error.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addError(subBuilder.buildPartial());
              break;
            }
            case 18: {
              org.technbolts.protobuf.UserPBModel.User.Builder subBuilder = org.technbolts.protobuf.UserPBModel.User.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addUser(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .org.technbolts.protobuf.Error error = 1;
      public java.util.List<org.technbolts.protobuf.CommonPBO.Error> getErrorList() {
        return java.util.Collections.unmodifiableList(result.error_);
      }
      public int getErrorCount() {
        return result.getErrorCount();
      }
      public org.technbolts.protobuf.CommonPBO.Error getError(int index) {
        return result.getError(index);
      }
      public Builder setError(int index, org.technbolts.protobuf.CommonPBO.Error value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.error_.set(index, value);
        return this;
      }
      public Builder setError(int index, org.technbolts.protobuf.CommonPBO.Error.Builder builderForValue) {
        result.error_.set(index, builderForValue.build());
        return this;
      }
      public Builder addError(org.technbolts.protobuf.CommonPBO.Error value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.error_.isEmpty()) {
          result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
        }
        result.error_.add(value);
        return this;
      }
      public Builder addError(org.technbolts.protobuf.CommonPBO.Error.Builder builderForValue) {
        if (result.error_.isEmpty()) {
          result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
        }
        result.error_.add(builderForValue.build());
        return this;
      }
      public Builder addAllError(
          java.lang.Iterable<? extends org.technbolts.protobuf.CommonPBO.Error> values) {
        if (result.error_.isEmpty()) {
          result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
        }
        super.addAll(values, result.error_);
        return this;
      }
      public Builder clearError() {
        result.error_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .org.technbolts.protobuf.User user = 2;
      public java.util.List<org.technbolts.protobuf.UserPBModel.User> getUserList() {
        return java.util.Collections.unmodifiableList(result.user_);
      }
      public int getUserCount() {
        return result.getUserCount();
      }
      public org.technbolts.protobuf.UserPBModel.User getUser(int index) {
        return result.getUser(index);
      }
      public Builder setUser(int index, org.technbolts.protobuf.UserPBModel.User value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.user_.set(index, value);
        return this;
      }
      public Builder setUser(int index, org.technbolts.protobuf.UserPBModel.User.Builder builderForValue) {
        result.user_.set(index, builderForValue.build());
        return this;
      }
      public Builder addUser(org.technbolts.protobuf.UserPBModel.User value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.user_.isEmpty()) {
          result.user_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.User>();
        }
        result.user_.add(value);
        return this;
      }
      public Builder addUser(org.technbolts.protobuf.UserPBModel.User.Builder builderForValue) {
        if (result.user_.isEmpty()) {
          result.user_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.User>();
        }
        result.user_.add(builderForValue.build());
        return this;
      }
      public Builder addAllUser(
          java.lang.Iterable<? extends org.technbolts.protobuf.UserPBModel.User> values) {
        if (result.user_.isEmpty()) {
          result.user_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.User>();
        }
        super.addAll(values, result.user_);
        return this;
      }
      public Builder clearUser() {
        result.user_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.CreateUserResponse)
    }
    
    static {
      defaultInstance = new CreateUserResponse(true);
      org.technbolts.protobuf.UserPBCommand.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.CreateUserResponse)
  }
  
  public static final class SearchUser extends
      com.google.protobuf.GeneratedMessage {
    // Use SearchUser.newBuilder() to construct.
    private SearchUser() {
      initFields();
    }
    private SearchUser(boolean noInit) {}
    
    private static final SearchUser defaultInstance;
    public static SearchUser getDefaultInstance() {
      return defaultInstance;
    }
    
    public SearchUser getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.UserPBCommand.internal_static_org_technbolts_protobuf_SearchUser_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.UserPBCommand.internal_static_org_technbolts_protobuf_SearchUser_fieldAccessorTable;
    }
    
    // optional .org.technbolts.protobuf.User sample = 1;
    public static final int SAMPLE_FIELD_NUMBER = 1;
    private boolean hasSample;
    private org.technbolts.protobuf.UserPBModel.User sample_;
    public boolean hasSample() { return hasSample; }
    public org.technbolts.protobuf.UserPBModel.User getSample() { return sample_; }
    
    // optional .org.technbolts.protobuf.Paging paging = 2;
    public static final int PAGING_FIELD_NUMBER = 2;
    private boolean hasPaging;
    private org.technbolts.protobuf.CommonPBO.Paging paging_;
    public boolean hasPaging() { return hasPaging; }
    public org.technbolts.protobuf.CommonPBO.Paging getPaging() { return paging_; }
    
    // optional bool id_only = 3 [default = false];
    public static final int ID_ONLY_FIELD_NUMBER = 3;
    private boolean hasIdOnly;
    private boolean idOnly_ = false;
    public boolean hasIdOnly() { return hasIdOnly; }
    public boolean getIdOnly() { return idOnly_; }
    
    private void initFields() {
      sample_ = org.technbolts.protobuf.UserPBModel.User.getDefaultInstance();
      paging_ = org.technbolts.protobuf.CommonPBO.Paging.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (hasSample()) {
        if (!getSample().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasSample()) {
        output.writeMessage(1, getSample());
      }
      if (hasPaging()) {
        output.writeMessage(2, getPaging());
      }
      if (hasIdOnly()) {
        output.writeBool(3, getIdOnly());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSample()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSample());
      }
      if (hasPaging()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPaging());
      }
      if (hasIdOnly()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, getIdOnly());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.UserPBCommand.SearchUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.SearchUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.SearchUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.SearchUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.SearchUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.SearchUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.SearchUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.UserPBCommand.SearchUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.UserPBCommand.SearchUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.SearchUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.UserPBCommand.SearchUser prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.UserPBCommand.SearchUser result;
      
      // Construct using org.technbolts.protobuf.UserPBCommand.SearchUser.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.UserPBCommand.SearchUser();
        return builder;
      }
      
      protected org.technbolts.protobuf.UserPBCommand.SearchUser internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.UserPBCommand.SearchUser();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.UserPBCommand.SearchUser.getDescriptor();
      }
      
      public org.technbolts.protobuf.UserPBCommand.SearchUser getDefaultInstanceForType() {
        return org.technbolts.protobuf.UserPBCommand.SearchUser.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.UserPBCommand.SearchUser build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.UserPBCommand.SearchUser buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.UserPBCommand.SearchUser buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        org.technbolts.protobuf.UserPBCommand.SearchUser returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.UserPBCommand.SearchUser) {
          return mergeFrom((org.technbolts.protobuf.UserPBCommand.SearchUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.UserPBCommand.SearchUser other) {
        if (other == org.technbolts.protobuf.UserPBCommand.SearchUser.getDefaultInstance()) return this;
        if (other.hasSample()) {
          mergeSample(other.getSample());
        }
        if (other.hasPaging()) {
          mergePaging(other.getPaging());
        }
        if (other.hasIdOnly()) {
          setIdOnly(other.getIdOnly());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              org.technbolts.protobuf.UserPBModel.User.Builder subBuilder = org.technbolts.protobuf.UserPBModel.User.newBuilder();
              if (hasSample()) {
                subBuilder.mergeFrom(getSample());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSample(subBuilder.buildPartial());
              break;
            }
            case 18: {
              org.technbolts.protobuf.CommonPBO.Paging.Builder subBuilder = org.technbolts.protobuf.CommonPBO.Paging.newBuilder();
              if (hasPaging()) {
                subBuilder.mergeFrom(getPaging());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPaging(subBuilder.buildPartial());
              break;
            }
            case 24: {
              setIdOnly(input.readBool());
              break;
            }
          }
        }
      }
      
      
      // optional .org.technbolts.protobuf.User sample = 1;
      public boolean hasSample() {
        return result.hasSample();
      }
      public org.technbolts.protobuf.UserPBModel.User getSample() {
        return result.getSample();
      }
      public Builder setSample(org.technbolts.protobuf.UserPBModel.User value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasSample = true;
        result.sample_ = value;
        return this;
      }
      public Builder setSample(org.technbolts.protobuf.UserPBModel.User.Builder builderForValue) {
        result.hasSample = true;
        result.sample_ = builderForValue.build();
        return this;
      }
      public Builder mergeSample(org.technbolts.protobuf.UserPBModel.User value) {
        if (result.hasSample() &&
            result.sample_ != org.technbolts.protobuf.UserPBModel.User.getDefaultInstance()) {
          result.sample_ =
            org.technbolts.protobuf.UserPBModel.User.newBuilder(result.sample_).mergeFrom(value).buildPartial();
        } else {
          result.sample_ = value;
        }
        result.hasSample = true;
        return this;
      }
      public Builder clearSample() {
        result.hasSample = false;
        result.sample_ = org.technbolts.protobuf.UserPBModel.User.getDefaultInstance();
        return this;
      }
      
      // optional .org.technbolts.protobuf.Paging paging = 2;
      public boolean hasPaging() {
        return result.hasPaging();
      }
      public org.technbolts.protobuf.CommonPBO.Paging getPaging() {
        return result.getPaging();
      }
      public Builder setPaging(org.technbolts.protobuf.CommonPBO.Paging value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasPaging = true;
        result.paging_ = value;
        return this;
      }
      public Builder setPaging(org.technbolts.protobuf.CommonPBO.Paging.Builder builderForValue) {
        result.hasPaging = true;
        result.paging_ = builderForValue.build();
        return this;
      }
      public Builder mergePaging(org.technbolts.protobuf.CommonPBO.Paging value) {
        if (result.hasPaging() &&
            result.paging_ != org.technbolts.protobuf.CommonPBO.Paging.getDefaultInstance()) {
          result.paging_ =
            org.technbolts.protobuf.CommonPBO.Paging.newBuilder(result.paging_).mergeFrom(value).buildPartial();
        } else {
          result.paging_ = value;
        }
        result.hasPaging = true;
        return this;
      }
      public Builder clearPaging() {
        result.hasPaging = false;
        result.paging_ = org.technbolts.protobuf.CommonPBO.Paging.getDefaultInstance();
        return this;
      }
      
      // optional bool id_only = 3 [default = false];
      public boolean hasIdOnly() {
        return result.hasIdOnly();
      }
      public boolean getIdOnly() {
        return result.getIdOnly();
      }
      public Builder setIdOnly(boolean value) {
        result.hasIdOnly = true;
        result.idOnly_ = value;
        return this;
      }
      public Builder clearIdOnly() {
        result.hasIdOnly = false;
        result.idOnly_ = false;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.SearchUser)
    }
    
    static {
      defaultInstance = new SearchUser(true);
      org.technbolts.protobuf.UserPBCommand.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.SearchUser)
  }
  
  public static final class SearchUserResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use SearchUserResponse.newBuilder() to construct.
    private SearchUserResponse() {
      initFields();
    }
    private SearchUserResponse(boolean noInit) {}
    
    private static final SearchUserResponse defaultInstance;
    public static SearchUserResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public SearchUserResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.UserPBCommand.internal_static_org_technbolts_protobuf_SearchUserResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.UserPBCommand.internal_static_org_technbolts_protobuf_SearchUserResponse_fieldAccessorTable;
    }
    
    // repeated .org.technbolts.protobuf.Error error = 1;
    public static final int ERROR_FIELD_NUMBER = 1;
    private java.util.List<org.technbolts.protobuf.CommonPBO.Error> error_ =
      java.util.Collections.emptyList();
    public java.util.List<org.technbolts.protobuf.CommonPBO.Error> getErrorList() {
      return error_;
    }
    public int getErrorCount() { return error_.size(); }
    public org.technbolts.protobuf.CommonPBO.Error getError(int index) {
      return error_.get(index);
    }
    
    // repeated uint32 user_id = 2;
    public static final int USER_ID_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> userId_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getUserIdList() {
      return userId_;
    }
    public int getUserIdCount() { return userId_.size(); }
    public int getUserId(int index) {
      return userId_.get(index);
    }
    
    // repeated .org.technbolts.protobuf.User user = 3;
    public static final int USER_FIELD_NUMBER = 3;
    private java.util.List<org.technbolts.protobuf.UserPBModel.User> user_ =
      java.util.Collections.emptyList();
    public java.util.List<org.technbolts.protobuf.UserPBModel.User> getUserList() {
      return user_;
    }
    public int getUserCount() { return user_.size(); }
    public org.technbolts.protobuf.UserPBModel.User getUser(int index) {
      return user_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      for (org.technbolts.protobuf.UserPBModel.User element : getUserList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (org.technbolts.protobuf.CommonPBO.Error element : getErrorList()) {
        output.writeMessage(1, element);
      }
      for (int element : getUserIdList()) {
        output.writeUInt32(2, element);
      }
      for (org.technbolts.protobuf.UserPBModel.User element : getUserList()) {
        output.writeMessage(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (org.technbolts.protobuf.CommonPBO.Error element : getErrorList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      {
        int dataSize = 0;
        for (int element : getUserIdList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getUserIdList().size();
      }
      for (org.technbolts.protobuf.UserPBModel.User element : getUserList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.UserPBCommand.SearchUserResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.SearchUserResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.SearchUserResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.SearchUserResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.SearchUserResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.SearchUserResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.SearchUserResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.UserPBCommand.SearchUserResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.UserPBCommand.SearchUserResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.SearchUserResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.UserPBCommand.SearchUserResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.UserPBCommand.SearchUserResponse result;
      
      // Construct using org.technbolts.protobuf.UserPBCommand.SearchUserResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.UserPBCommand.SearchUserResponse();
        return builder;
      }
      
      protected org.technbolts.protobuf.UserPBCommand.SearchUserResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.UserPBCommand.SearchUserResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.UserPBCommand.SearchUserResponse.getDescriptor();
      }
      
      public org.technbolts.protobuf.UserPBCommand.SearchUserResponse getDefaultInstanceForType() {
        return org.technbolts.protobuf.UserPBCommand.SearchUserResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.UserPBCommand.SearchUserResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.UserPBCommand.SearchUserResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.UserPBCommand.SearchUserResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.error_ != java.util.Collections.EMPTY_LIST) {
          result.error_ =
            java.util.Collections.unmodifiableList(result.error_);
        }
        if (result.userId_ != java.util.Collections.EMPTY_LIST) {
          result.userId_ =
            java.util.Collections.unmodifiableList(result.userId_);
        }
        if (result.user_ != java.util.Collections.EMPTY_LIST) {
          result.user_ =
            java.util.Collections.unmodifiableList(result.user_);
        }
        org.technbolts.protobuf.UserPBCommand.SearchUserResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.UserPBCommand.SearchUserResponse) {
          return mergeFrom((org.technbolts.protobuf.UserPBCommand.SearchUserResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.UserPBCommand.SearchUserResponse other) {
        if (other == org.technbolts.protobuf.UserPBCommand.SearchUserResponse.getDefaultInstance()) return this;
        if (!other.error_.isEmpty()) {
          if (result.error_.isEmpty()) {
            result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
          }
          result.error_.addAll(other.error_);
        }
        if (!other.userId_.isEmpty()) {
          if (result.userId_.isEmpty()) {
            result.userId_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.userId_.addAll(other.userId_);
        }
        if (!other.user_.isEmpty()) {
          if (result.user_.isEmpty()) {
            result.user_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.User>();
          }
          result.user_.addAll(other.user_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              org.technbolts.protobuf.CommonPBO.Error.Builder subBuilder = org.technbolts.protobuf.CommonPBO.Error.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addError(subBuilder.buildPartial());
              break;
            }
            case 16: {
              addUserId(input.readUInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addUserId(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 26: {
              org.technbolts.protobuf.UserPBModel.User.Builder subBuilder = org.technbolts.protobuf.UserPBModel.User.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addUser(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .org.technbolts.protobuf.Error error = 1;
      public java.util.List<org.technbolts.protobuf.CommonPBO.Error> getErrorList() {
        return java.util.Collections.unmodifiableList(result.error_);
      }
      public int getErrorCount() {
        return result.getErrorCount();
      }
      public org.technbolts.protobuf.CommonPBO.Error getError(int index) {
        return result.getError(index);
      }
      public Builder setError(int index, org.technbolts.protobuf.CommonPBO.Error value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.error_.set(index, value);
        return this;
      }
      public Builder setError(int index, org.technbolts.protobuf.CommonPBO.Error.Builder builderForValue) {
        result.error_.set(index, builderForValue.build());
        return this;
      }
      public Builder addError(org.technbolts.protobuf.CommonPBO.Error value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.error_.isEmpty()) {
          result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
        }
        result.error_.add(value);
        return this;
      }
      public Builder addError(org.technbolts.protobuf.CommonPBO.Error.Builder builderForValue) {
        if (result.error_.isEmpty()) {
          result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
        }
        result.error_.add(builderForValue.build());
        return this;
      }
      public Builder addAllError(
          java.lang.Iterable<? extends org.technbolts.protobuf.CommonPBO.Error> values) {
        if (result.error_.isEmpty()) {
          result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
        }
        super.addAll(values, result.error_);
        return this;
      }
      public Builder clearError() {
        result.error_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated uint32 user_id = 2;
      public java.util.List<java.lang.Integer> getUserIdList() {
        return java.util.Collections.unmodifiableList(result.userId_);
      }
      public int getUserIdCount() {
        return result.getUserIdCount();
      }
      public int getUserId(int index) {
        return result.getUserId(index);
      }
      public Builder setUserId(int index, int value) {
        result.userId_.set(index, value);
        return this;
      }
      public Builder addUserId(int value) {
        if (result.userId_.isEmpty()) {
          result.userId_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.userId_.add(value);
        return this;
      }
      public Builder addAllUserId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.userId_.isEmpty()) {
          result.userId_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.userId_);
        return this;
      }
      public Builder clearUserId() {
        result.userId_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .org.technbolts.protobuf.User user = 3;
      public java.util.List<org.technbolts.protobuf.UserPBModel.User> getUserList() {
        return java.util.Collections.unmodifiableList(result.user_);
      }
      public int getUserCount() {
        return result.getUserCount();
      }
      public org.technbolts.protobuf.UserPBModel.User getUser(int index) {
        return result.getUser(index);
      }
      public Builder setUser(int index, org.technbolts.protobuf.UserPBModel.User value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.user_.set(index, value);
        return this;
      }
      public Builder setUser(int index, org.technbolts.protobuf.UserPBModel.User.Builder builderForValue) {
        result.user_.set(index, builderForValue.build());
        return this;
      }
      public Builder addUser(org.technbolts.protobuf.UserPBModel.User value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.user_.isEmpty()) {
          result.user_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.User>();
        }
        result.user_.add(value);
        return this;
      }
      public Builder addUser(org.technbolts.protobuf.UserPBModel.User.Builder builderForValue) {
        if (result.user_.isEmpty()) {
          result.user_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.User>();
        }
        result.user_.add(builderForValue.build());
        return this;
      }
      public Builder addAllUser(
          java.lang.Iterable<? extends org.technbolts.protobuf.UserPBModel.User> values) {
        if (result.user_.isEmpty()) {
          result.user_ = new java.util.ArrayList<org.technbolts.protobuf.UserPBModel.User>();
        }
        super.addAll(values, result.user_);
        return this;
      }
      public Builder clearUser() {
        result.user_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.SearchUserResponse)
    }
    
    static {
      defaultInstance = new SearchUserResponse(true);
      org.technbolts.protobuf.UserPBCommand.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.SearchUserResponse)
  }
  
  public static final class DeleteUser extends
      com.google.protobuf.GeneratedMessage {
    // Use DeleteUser.newBuilder() to construct.
    private DeleteUser() {
      initFields();
    }
    private DeleteUser(boolean noInit) {}
    
    private static final DeleteUser defaultInstance;
    public static DeleteUser getDefaultInstance() {
      return defaultInstance;
    }
    
    public DeleteUser getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.UserPBCommand.internal_static_org_technbolts_protobuf_DeleteUser_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.UserPBCommand.internal_static_org_technbolts_protobuf_DeleteUser_fieldAccessorTable;
    }
    
    // repeated uint32 user_id = 2;
    public static final int USER_ID_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> userId_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getUserIdList() {
      return userId_;
    }
    public int getUserIdCount() { return userId_.size(); }
    public int getUserId(int index) {
      return userId_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int element : getUserIdList()) {
        output.writeUInt32(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int element : getUserIdList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getUserIdList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.UserPBCommand.DeleteUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.DeleteUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.DeleteUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.DeleteUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.DeleteUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.DeleteUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.DeleteUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.UserPBCommand.DeleteUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.UserPBCommand.DeleteUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.DeleteUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.UserPBCommand.DeleteUser prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.UserPBCommand.DeleteUser result;
      
      // Construct using org.technbolts.protobuf.UserPBCommand.DeleteUser.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.UserPBCommand.DeleteUser();
        return builder;
      }
      
      protected org.technbolts.protobuf.UserPBCommand.DeleteUser internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.UserPBCommand.DeleteUser();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.UserPBCommand.DeleteUser.getDescriptor();
      }
      
      public org.technbolts.protobuf.UserPBCommand.DeleteUser getDefaultInstanceForType() {
        return org.technbolts.protobuf.UserPBCommand.DeleteUser.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.UserPBCommand.DeleteUser build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.UserPBCommand.DeleteUser buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.UserPBCommand.DeleteUser buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.userId_ != java.util.Collections.EMPTY_LIST) {
          result.userId_ =
            java.util.Collections.unmodifiableList(result.userId_);
        }
        org.technbolts.protobuf.UserPBCommand.DeleteUser returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.UserPBCommand.DeleteUser) {
          return mergeFrom((org.technbolts.protobuf.UserPBCommand.DeleteUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.UserPBCommand.DeleteUser other) {
        if (other == org.technbolts.protobuf.UserPBCommand.DeleteUser.getDefaultInstance()) return this;
        if (!other.userId_.isEmpty()) {
          if (result.userId_.isEmpty()) {
            result.userId_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.userId_.addAll(other.userId_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 16: {
              addUserId(input.readUInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addUserId(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // repeated uint32 user_id = 2;
      public java.util.List<java.lang.Integer> getUserIdList() {
        return java.util.Collections.unmodifiableList(result.userId_);
      }
      public int getUserIdCount() {
        return result.getUserIdCount();
      }
      public int getUserId(int index) {
        return result.getUserId(index);
      }
      public Builder setUserId(int index, int value) {
        result.userId_.set(index, value);
        return this;
      }
      public Builder addUserId(int value) {
        if (result.userId_.isEmpty()) {
          result.userId_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.userId_.add(value);
        return this;
      }
      public Builder addAllUserId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.userId_.isEmpty()) {
          result.userId_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.userId_);
        return this;
      }
      public Builder clearUserId() {
        result.userId_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.DeleteUser)
    }
    
    static {
      defaultInstance = new DeleteUser(true);
      org.technbolts.protobuf.UserPBCommand.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.DeleteUser)
  }
  
  public static final class DeleteUserResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use DeleteUserResponse.newBuilder() to construct.
    private DeleteUserResponse() {
      initFields();
    }
    private DeleteUserResponse(boolean noInit) {}
    
    private static final DeleteUserResponse defaultInstance;
    public static DeleteUserResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public DeleteUserResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.technbolts.protobuf.UserPBCommand.internal_static_org_technbolts_protobuf_DeleteUserResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.technbolts.protobuf.UserPBCommand.internal_static_org_technbolts_protobuf_DeleteUserResponse_fieldAccessorTable;
    }
    
    // repeated .org.technbolts.protobuf.Error error = 1;
    public static final int ERROR_FIELD_NUMBER = 1;
    private java.util.List<org.technbolts.protobuf.CommonPBO.Error> error_ =
      java.util.Collections.emptyList();
    public java.util.List<org.technbolts.protobuf.CommonPBO.Error> getErrorList() {
      return error_;
    }
    public int getErrorCount() { return error_.size(); }
    public org.technbolts.protobuf.CommonPBO.Error getError(int index) {
      return error_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (org.technbolts.protobuf.CommonPBO.Error element : getErrorList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (org.technbolts.protobuf.CommonPBO.Error element : getErrorList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.technbolts.protobuf.UserPBCommand.DeleteUserResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.DeleteUserResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.DeleteUserResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.DeleteUserResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.DeleteUserResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.DeleteUserResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.DeleteUserResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.UserPBCommand.DeleteUserResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.technbolts.protobuf.UserPBCommand.DeleteUserResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.technbolts.protobuf.UserPBCommand.DeleteUserResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.technbolts.protobuf.UserPBCommand.DeleteUserResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.technbolts.protobuf.UserPBCommand.DeleteUserResponse result;
      
      // Construct using org.technbolts.protobuf.UserPBCommand.DeleteUserResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.technbolts.protobuf.UserPBCommand.DeleteUserResponse();
        return builder;
      }
      
      protected org.technbolts.protobuf.UserPBCommand.DeleteUserResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.technbolts.protobuf.UserPBCommand.DeleteUserResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.technbolts.protobuf.UserPBCommand.DeleteUserResponse.getDescriptor();
      }
      
      public org.technbolts.protobuf.UserPBCommand.DeleteUserResponse getDefaultInstanceForType() {
        return org.technbolts.protobuf.UserPBCommand.DeleteUserResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.technbolts.protobuf.UserPBCommand.DeleteUserResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.technbolts.protobuf.UserPBCommand.DeleteUserResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.technbolts.protobuf.UserPBCommand.DeleteUserResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.error_ != java.util.Collections.EMPTY_LIST) {
          result.error_ =
            java.util.Collections.unmodifiableList(result.error_);
        }
        org.technbolts.protobuf.UserPBCommand.DeleteUserResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.technbolts.protobuf.UserPBCommand.DeleteUserResponse) {
          return mergeFrom((org.technbolts.protobuf.UserPBCommand.DeleteUserResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.technbolts.protobuf.UserPBCommand.DeleteUserResponse other) {
        if (other == org.technbolts.protobuf.UserPBCommand.DeleteUserResponse.getDefaultInstance()) return this;
        if (!other.error_.isEmpty()) {
          if (result.error_.isEmpty()) {
            result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
          }
          result.error_.addAll(other.error_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              org.technbolts.protobuf.CommonPBO.Error.Builder subBuilder = org.technbolts.protobuf.CommonPBO.Error.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addError(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .org.technbolts.protobuf.Error error = 1;
      public java.util.List<org.technbolts.protobuf.CommonPBO.Error> getErrorList() {
        return java.util.Collections.unmodifiableList(result.error_);
      }
      public int getErrorCount() {
        return result.getErrorCount();
      }
      public org.technbolts.protobuf.CommonPBO.Error getError(int index) {
        return result.getError(index);
      }
      public Builder setError(int index, org.technbolts.protobuf.CommonPBO.Error value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.error_.set(index, value);
        return this;
      }
      public Builder setError(int index, org.technbolts.protobuf.CommonPBO.Error.Builder builderForValue) {
        result.error_.set(index, builderForValue.build());
        return this;
      }
      public Builder addError(org.technbolts.protobuf.CommonPBO.Error value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.error_.isEmpty()) {
          result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
        }
        result.error_.add(value);
        return this;
      }
      public Builder addError(org.technbolts.protobuf.CommonPBO.Error.Builder builderForValue) {
        if (result.error_.isEmpty()) {
          result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
        }
        result.error_.add(builderForValue.build());
        return this;
      }
      public Builder addAllError(
          java.lang.Iterable<? extends org.technbolts.protobuf.CommonPBO.Error> values) {
        if (result.error_.isEmpty()) {
          result.error_ = new java.util.ArrayList<org.technbolts.protobuf.CommonPBO.Error>();
        }
        super.addAll(values, result.error_);
        return this;
      }
      public Builder clearError() {
        result.error_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.technbolts.protobuf.DeleteUserResponse)
    }
    
    static {
      defaultInstance = new DeleteUserResponse(true);
      org.technbolts.protobuf.UserPBCommand.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.technbolts.protobuf.DeleteUserResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_CreateUser_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_CreateUser_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_CreateUserResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_CreateUserResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_SearchUser_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_SearchUser_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_SearchUserResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_SearchUserResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_DeleteUser_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_DeleteUser_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_technbolts_protobuf_DeleteUserResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_technbolts_protobuf_DeleteUserResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023user/user-api.proto\022\027org.technbolts.pr" +
      "otobuf\032\014common.proto\032\021user/models.proto\"" +
      "Q\n\nCreateUser\022+\n\004user\030\001 \003(\0132\035.org.technb" +
      "olts.protobuf.User\022\026\n\007id_only\030\002 \001(\010:\005fal" +
      "se\"p\n\022CreateUserResponse\022-\n\005error\030\001 \003(\0132" +
      "\036.org.technbolts.protobuf.Error\022+\n\004user\030" +
      "\002 \003(\0132\035.org.technbolts.protobuf.User\"\204\001\n" +
      "\nSearchUser\022-\n\006sample\030\001 \001(\0132\035.org.technb" +
      "olts.protobuf.User\022/\n\006paging\030\002 \001(\0132\037.org" +
      ".technbolts.protobuf.Paging\022\026\n\007id_only\030\003",
      " \001(\010:\005false\"\201\001\n\022SearchUserResponse\022-\n\005er" +
      "ror\030\001 \003(\0132\036.org.technbolts.protobuf.Erro" +
      "r\022\017\n\007user_id\030\002 \003(\r\022+\n\004user\030\003 \003(\0132\035.org.t" +
      "echnbolts.protobuf.User\"\035\n\nDeleteUser\022\017\n" +
      "\007user_id\030\002 \003(\r\"C\n\022DeleteUserResponse\022-\n\005" +
      "error\030\001 \003(\0132\036.org.technbolts.protobuf.Er" +
      "rorB*\n\027org.technbolts.protobufB\rUserPBCo" +
      "mmandH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_technbolts_protobuf_CreateUser_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_technbolts_protobuf_CreateUser_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_CreateUser_descriptor,
              new java.lang.String[] { "User", "IdOnly", },
              org.technbolts.protobuf.UserPBCommand.CreateUser.class,
              org.technbolts.protobuf.UserPBCommand.CreateUser.Builder.class);
          internal_static_org_technbolts_protobuf_CreateUserResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_technbolts_protobuf_CreateUserResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_CreateUserResponse_descriptor,
              new java.lang.String[] { "Error", "User", },
              org.technbolts.protobuf.UserPBCommand.CreateUserResponse.class,
              org.technbolts.protobuf.UserPBCommand.CreateUserResponse.Builder.class);
          internal_static_org_technbolts_protobuf_SearchUser_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_org_technbolts_protobuf_SearchUser_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_SearchUser_descriptor,
              new java.lang.String[] { "Sample", "Paging", "IdOnly", },
              org.technbolts.protobuf.UserPBCommand.SearchUser.class,
              org.technbolts.protobuf.UserPBCommand.SearchUser.Builder.class);
          internal_static_org_technbolts_protobuf_SearchUserResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_org_technbolts_protobuf_SearchUserResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_SearchUserResponse_descriptor,
              new java.lang.String[] { "Error", "UserId", "User", },
              org.technbolts.protobuf.UserPBCommand.SearchUserResponse.class,
              org.technbolts.protobuf.UserPBCommand.SearchUserResponse.Builder.class);
          internal_static_org_technbolts_protobuf_DeleteUser_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_org_technbolts_protobuf_DeleteUser_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_DeleteUser_descriptor,
              new java.lang.String[] { "UserId", },
              org.technbolts.protobuf.UserPBCommand.DeleteUser.class,
              org.technbolts.protobuf.UserPBCommand.DeleteUser.Builder.class);
          internal_static_org_technbolts_protobuf_DeleteUserResponse_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_org_technbolts_protobuf_DeleteUserResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_technbolts_protobuf_DeleteUserResponse_descriptor,
              new java.lang.String[] { "Error", },
              org.technbolts.protobuf.UserPBCommand.DeleteUserResponse.class,
              org.technbolts.protobuf.UserPBCommand.DeleteUserResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.technbolts.protobuf.CommonPBO.getDescriptor(),
          org.technbolts.protobuf.UserPBModel.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
